Refactor ClearML NMT build job
sillsdev/machine pull request #101
Opened 2023-10-03 21:55 UTC by ddaspit

- add support for multiple build stages
- add support for running build jobs on Hangfire or ClearML
- add BuildJobService
- categorize build jobs into CPU or GPU jobs
- decouple build job runners from translation engines
- fix issues with S3FileStorage
- fix issues with ClearMLService

2023-10-04 16:58 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfvc4PEDTa5tGxB8GlH:-Nfvc4PEDTa5tGxB8GlI:bqwgwdm) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L72)):*
> ```Smalltalk
>             return builder.AddThotSmtModel(o => { });
>         else
>             return builder.AddThotSmtModel(builder.Configuration.GetSection(ThotSmtModelOptions.Key));
> ```

Damien - can you explain what is happening here?  Modifying the SMT models is not specified in the commit messages.


<!-- Sent from Reviewable.io -->

2023-10-04 17:02 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvcxzvCqH_4FbhUJHf:-NfvcxzvCqH_4FbhUJHg:bb415tt) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L9)):*
> ```Smalltalk
>     public string EngineId { get; set; } = default!;
>     public string SourceLanguage { get; set; } = default!;
>     public string TargetLanguage { get; set; } = default!;
> ```

Won't this break all existing builds in the Mongo DB?  Should just clear everything out or do we need a migration plan?


<!-- Sent from Reviewable.io -->

2023-10-04 17:13 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 44 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvfV5oCezcyyjf-wXp:-NfvfV5oCezcyyjf-wXq:bntga1u) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L44)):*
> ```Smalltalk
>     protected override void Started()
>     {
>         _logger.LogInformation("ClearML authentication service started.");
> ```

These functions do nothing.  Should they be removed?


<!-- Sent from Reviewable.io -->

2023-10-04 17:13 UTC, johnml1135 requested changes
> Reviewed 14 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-04 17:17 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvgPG_0MuNLnXoj0lb:-NfvgPG_0MuNLnXoj0lc:b-1cxjsy) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L32)):*
> ```Smalltalk
>     protected override void Started()
>     {
>         _logger.LogInformation("ClearML monitor service started.");
> ```

Are these supposed to do more than just log?


<!-- Sent from Reviewable.io -->

2023-10-04 18:18 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvgPG_0MuNLnXoj0lb:-NfvuHfe11mxgxZiN_V7:b-80a8gl) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Are these supposed to do more than just log?
</blockquote></details>

Could this be defined once in RecurrentTask and only overridden if necessary?


<!-- Sent from Reviewable.io -->

2023-10-04 18:37 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvyeGr6Gp4U1-tiJPP:-NfvyeGr6Gp4U1-tiJPQ:b-uj89h5) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L23)):*
> ```Smalltalk
>     }
> 
>     [Queue("nmt")]
> ```

Can this be thread limited to 1.5 threads?  Or configurable from app settings as a float?


<!-- Sent from Reviewable.io -->

2023-10-04 18:44 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfw-CCi2zcpxLJX8lE7:-Nfw-CCi2zcpxLJX8lE8:b5q0esg) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj#L37)):*
> ```XML
> 		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.16" />
> 		<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.14" />
> 		<PackageReference Include="Python.Included" Version="3.11.4" />
> ```

Can you add a issue for completing this Python code?  If it is incomplete, it should have an attached issue.


<!-- Sent from Reviewable.io -->

2023-10-04 22:37 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: 54 of 66 files reviewed, 6 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfw-CCi2zcpxLJX8lE7:-Nfwp2zpDF_cvxISc9hH:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you add a issue for completing this Python code?  If it is incomplete, it should have an attached issue.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfvc4PEDTa5tGxB8GlH:-NfwfTAlAFsSwf-zfQqL:b925b0m) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Damien - can you explain what is happening here?  Modifying the SMT models is not specified in the commit messages.
</blockquote></details>

This is just a refactoring of the configuration for the Thot SMT model to make it more consistent with the way that other services are configured.
___
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvcxzvCqH_4FbhUJHf:-NfwfhU3B317AJEaPu-c:b-s6mp4k) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Won't this break all existing builds in the Mongo DB?  Should just clear everything out or do we need a migration plan?
</blockquote></details>

That is a good question. Migrating would be simple. I think it would only require us to remove the `BuildState` and `IsCanceled` properties from all engines.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs` line 44 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvfV5oCezcyyjf-wXp:-Nfwp4Kj90kXck66IFgg:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/ClearMLAuthenticationService.cs#L44)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

These functions do nothing.  Should they be removed?
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvgPG_0MuNLnXoj0lb:-Nfwp5VT4jRZZ32QXuOZ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Could this be defined once in RecurrentTask and only overridden if necessary?
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvyeGr6Gp4U1-tiJPP:-NfwmT9R536ZgGhTk71K:blo3w7y) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L23)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can this be thread limited to 1.5 threads?  Or configurable from app settings as a float?
</blockquote></details>

You can [configure](https://docs.hangfire.io/en/latest/background-processing/configuring-degree-of-parallelism.html) the number of workers that are available for Hangfire. The default is `Math.Min(Environment.ProcessorCount * 5, MaxDefaultWorkerCount)`.


<!-- Sent from Reviewable.io -->

2023-10-05 16:16 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 169 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-bwUh1rjPsE1hwAnS:-Ng-bwUh1rjPsE1hwAnT:b-nrt0qf) ([raw file](https://github.com/sillsdev/machine/blob/62ddd19b96ee3362f38491968fce834efbd9e93e/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L169)):*
> ```Smalltalk
>         if (metrics is null)
>             throw new InvalidOperationException("Malformed response from ClearML server.");
>         var performanceMetrics = (JsonObject?)metrics.FirstOrDefault(m => (string?)m?["name"] == "metrics");
> ```

So, you have the new metrics code - does it do the same thing?  Where is all the parsing of the results?  I can't find it.


<!-- Sent from Reviewable.io -->

2023-10-05 16:21 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: 54 of 66 files reviewed, 7 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 169 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-bwUh1rjPsE1hwAnS:-Ng-cqJu9JHJ6AAIEPDx:b-nocioz) ([raw file](https://github.com/sillsdev/machine/blob/62ddd19b96ee3362f38491968fce834efbd9e93e/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L169)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, you have the new metrics code - does it do the same thing?  Where is all the parsing of the results?  I can't find it.
</blockquote></details>

There is a `GetMetric` method in the `ClearMLMonitorService` class that reads a metric from a task.


<!-- Sent from Reviewable.io -->

2023-10-05 16:27 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/HangfireBuildJobRunner.cs` line 37 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-edj--sumFTb7LgDG:-Ng-edj--sumFTb7LgDH:b-8vejtc) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/HangfireBuildJobRunner.cs#L37)):*
> ```Smalltalk
>     public Task CreateEngineAsync(string engineId, string? name = null, CancellationToken cancellationToken = default)
>     {
>         return Task.CompletedTask;
> ```

How is this creating an engine?


<!-- Sent from Reviewable.io -->

2023-10-05 17:19 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-qQYn7kk-zwqvkfjX:-Ng-qQYn7kk-zwqvkfjY:b3h57b) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L64)):*
> ```Smalltalk
>     public async Task DeleteAsync(string engineId, CancellationToken cancellationToken = default)
>     {
>         await _dataAccessContext.BeginTransactionAsync(cancellationToken);
> ```

Should we first check to see if we need to cancel any jobs?  Is that done somewhere else?


<!-- Sent from Reviewable.io -->

2023-10-05 17:28 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs` line 23 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvyeGr6Gp4U1-tiJPP:-Ng-sWcd7MWQQv7EEufT:b-9cropd) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs#L23)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can [configure](https://docs.hangfire.io/en/latest/background-processing/configuring-degree-of-parallelism.html) the number of workers that are available for Hangfire. The default is `Math.Min(Environment.ProcessorCount * 5, MaxDefaultWorkerCount)`.
</blockquote></details>

https://github.com/sillsdev/serval/issues/154 - opened an issue to see if this will be a problem.


<!-- Sent from Reviewable.io -->

2023-10-05 17:33 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtTrainBuildJob.cs` line 60 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-sm4bCfq7NGUyVftK:-Ng-sm4bCfq7NGUyVftL:bl9zc5h) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/NmtTrainBuildJob.cs#L60)):*
> ```Smalltalk
>             using (Py.GIL())
>             {
>                 PythonEngine.Exec(
> ```

We need to finish this here: https://github.com/sillsdev/machine/issues/105.


<!-- Sent from Reviewable.io -->

2023-10-05 17:43 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 69 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-vnbw8telk3Uey7X4:-Ng-vnbw8telk3Uey7X5:b-6wnbt1) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L69)):*
> ```Smalltalk
> 
>     public async Task DeleteAsync(string engineId, CancellationToken cancellationToken = default)
>     {
> ```

There is no code coverage in CI for this.  Probably a test or two could be added to cover deleting an engine with a build running.


<!-- Sent from Reviewable.io -->

2023-10-05 17:45 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 150 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wLb99WnGadyf-QM1:-Ng-wLb99WnGadyf-QM2:b-4fe9ql) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L150)):*
> ```Smalltalk
>             TranslationEngine engine = await GetEngineAsync(engineId, cancellationToken);
>             if (engine.CurrentBuild?.JobState is BuildJobState.Active)
>             {
> ```

I know there are almost no changes, but there are no CI tests for training a segment while the engine is building.


<!-- Sent from Reviewable.io -->

2023-10-05 17:47 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 223 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wYIW-_cJn_Aar3Pw:-Ng-wYIW-_cJn_Aar3Px:b-9q6ixb) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L223)):*
> ```Smalltalk
>     )
>     {
>         using ISubscription<TranslationEngine> sub = await _engines.SubscribeAsync(
> ```

There are no tests to cover this function.


<!-- Sent from Reviewable.io -->

2023-10-05 17:55 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 223 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wYIW-_cJn_Aar3Pw:-Ng-yJU13ULMEKO7mqIt:b-9qi9mp) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L223)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There are no tests to cover this function.
</blockquote></details>

Though it should be covered in CancelBuildAsync.  What gives?


<!-- Sent from Reviewable.io -->

2023-10-05 17:56 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 223 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wYIW-_cJn_Aar3Pw:-Ng-yn_66jsk8nxLgXWe:basj1fd) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L223)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Though it should be covered in CancelBuildAsync.  What gives?
</blockquote></details>

Nevermind - it's covered in DeleteAsync when a job is currently running, is cancelled and then we need to wait for it to finish up.  A test covering that should suffice.


<!-- Sent from Reviewable.io -->

2023-10-05 17:58 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineStateService.cs` line 51 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-zKqX8ZR1wmOgzRm-:-Ng-zKqX8ZR1wmOgzRm0:b-u5i3g) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineStateService.cs#L51)):*
> ```Smalltalk
>                 if (
>                     engine is not null
>                     && (engine.CurrentBuild is null || engine.CurrentBuild.JobState is BuildJobState.Pending)
> ```

Any particular reason for the change in logic here?  Why current build is null or jobstate is pending from just not active?


<!-- Sent from Reviewable.io -->

2023-10-05 18:04 UTC, johnml1135 commented
*[`src/SIL.Machine.Serval.EngineServer/appsettings.json` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng0-QUm0PRm9k-e5Z_Z:-Ng0-QUm0PRm9k-e5Z__:bkkjbbx) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.EngineServer/appsettings.json#L21)):*
> ```JSON
>   "ClearML": {
>     "ApiServer": "https://api.sil.hosted.allegro.ai",
>     "Queue": "production",
> ```

This should be overridden in either development app settings or in env variables.  I would remove queue and docker image - let the program fail if they are not defined.


<!-- Sent from Reviewable.io -->

2023-10-05 18:04 UTC, johnml1135 commented
*[`src/SIL.Machine.Serval.EngineServer/appsettings.json` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng0-QUm0PRm9k-e5Z_Z:-Ng0-k9c-2AyltXgrxq8:bul507) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.EngineServer/appsettings.json#L21)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should be overridden in either development app settings or in env variables.  I would remove queue and docker image - let the program fail if they are not defined.
</blockquote></details>

And remove s3 uri - that changes based upon environment.


<!-- Sent from Reviewable.io -->

2023-10-05 18:15 UTC, johnml1135 commented
*[`src/SIL.Machine.Serval.JobServer/appsettings.json` line 22 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng00cDm8GVdR1_aLHNt:-Ng00cDm8GVdR1_aLHNu:bdi8wa5) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.JobServer/appsettings.json#L22)):*
> ```JSON
>     "ApiServer": "https://api.sil.hosted.allegro.ai",
>     "Queue": "production",
>     "DockerImage": "ghcr.io/sillsdev/machine.py:0.9.3.3",
> ```

Remove queue, docker image and sharedfile.


<!-- Sent from Reviewable.io -->

2023-10-05 18:18 UTC, johnml1135 commented
*[`src/SIL.Machine.Serval.JobServer/appsettings.json` line 23 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng02NIJC-mtF31c93MQ:-Ng02x9B1o-4IW-vN11j:b-32eej7) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.JobServer/appsettings.json#L23)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why is the timeout set to 0?  It will never run!
</blockquote></details>

Actually, it will throw an exception when making the periodic timer: https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer.-ctor?view=net-7.0


<!-- Sent from Reviewable.io -->

2023-10-05 18:22 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs` line 49 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng03mv_1LgKl0gioax0:-Ng03mv_1LgKl0gioax1:bng9htt) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs#L49)):*
> ```Smalltalk
>         Assert.That(engine.BuildRevision, Is.EqualTo(1));
>     }
> ```

There should be a test to delete an engine after a build has started.


<!-- Sent from Reviewable.io -->

2023-10-05 18:24 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfw-CCi2zcpxLJX8lE7:-Ng04Hc39FpjfnG3jEaH:b-djpppy) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj#L37)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I started an issue here - https://github.com/sillsdev/machine/issues/105.  Where is your issue?


<!-- Sent from Reviewable.io -->

2023-10-05 18:25 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvcxzvCqH_4FbhUJHf:-Ng04QBJ5y-zZzRClwz0:b-3qi1bi) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

That is a good question. Migrating would be simple. I think it would only require us to remove the `BuildState` and `IsCanceled` properties from all engines.
</blockquote></details>

Or, would the states just be ignored?  Should they be transitioned?  Maybe keep the old parameters and check at initialization if the depreciated fields are there - and then transition them?


<!-- Sent from Reviewable.io -->

2023-10-05 18:37 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLService.cs` line 169 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-bwUh1rjPsE1hwAnS:-Ng05-gV6hkNdI7JE67B:b-ila89p) ([raw file](https://github.com/sillsdev/machine/blob/62ddd19b96ee3362f38491968fce834efbd9e93e/src/SIL.Machine.AspNetCore/Services/ClearMLService.cs#L169)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is a `GetMetric` method in the `ClearMLMonitorService` class that reads a metric from a task.
</blockquote></details>

Whatever it is, it looks more elegant.  I am assuming it will get tested in E2E testing.


<!-- Sent from Reviewable.io -->

2023-10-05 18:37 UTC, johnml1135 reviewed
> Reviewed 42 of 66 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: all files reviewed, 12 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-05 22:17 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: 58 of 66 files reviewed, 12 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj` line 37 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-Nfw-CCi2zcpxLJX8lE7:-Ng0ClQC6VmgNZSajC-H:badqoin) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/SIL.Machine.AspNetCore.csproj#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I started an issue here - https://github.com/sillsdev/machine/issues/105.  Where is your issue?
</blockquote></details>

The issue is https://github.com/sillsdev/machine/issues/103.
___
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/101#-NfvcxzvCqH_4FbhUJHf:-Ng0sGmaElmBGifAWSc4:b-91nnef) ([raw file](https://github.com/sillsdev/machine/blob/957a85d663cb953866a416f62e5413976bea690a/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Or, would the states just be ignored?  Should they be transitioned?  Maybe keep the old parameters and check at initialization if the depreciated fields are there - and then transition them?
</blockquote></details>

I don't think it is worth migrating them. They are only used when a build is running. When we upgrade, we will shut everything down, so there won't be any running builds. If we don't remove them, the Mongo driver will throw an exception when it tries to deserialize a translation engine doc into a model. I added `SetIgnoreExtraElements(true)` to the `TranslationEngine` map. This will cause the Mongo driver to ignore the old properties. We won't need to migrate or remove the properties.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-qQYn7kk-zwqvkfjX:-Ng0HXMD7Z8GQ-2cNXDl:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L64)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should we first check to see if we need to cancel any jobs?  Is that done somewhere else?
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 69 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-vnbw8telk3Uey7X4:-Ng0dUuh03cFsanHsb08:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L69)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There is no code coverage in CI for this.  Probably a test or two could be added to cover deleting an engine with a build running.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 118 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-w-Pf8wlHWQpim9ts:-Ng0KER7Ez6gB0xdXRgl:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L118)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There is no CI coverage for this function.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 150 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wLb99WnGadyf-QM1:-Ng0irP-7qncqdc3xnb-:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L150)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I know there are almost no changes, but there are no CI tests for training a segment while the engine is building.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 223 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wYIW-_cJn_Aar3Pw:-Ng0dYflDIDwKvOT2tDv:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L223)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Nevermind - it's covered in DeleteAsync when a job is currently running, is cancelled and then we need to wait for it to finish up.  A test covering that should suffice.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineStateService.cs` line 51 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-zKqX8ZR1wmOgzRm-:-Ng0IPUv0rDYgcAiaduP:b-huaaqc) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineStateService.cs#L51)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Any particular reason for the change in logic here?  Why current build is null or jobstate is pending from just not active?
</blockquote></details>

This was updated, because of the addition of the canceling state.
___
*[`src/SIL.Machine.Serval.EngineServer/appsettings.json` line 21 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng0-QUm0PRm9k-e5Z_Z:-Ng0IUj-0CMgw-2zpQx_:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.EngineServer/appsettings.json#L21)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

And remove s3 uri - that changes based upon environment.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.Serval.JobServer/appsettings.json` line 22 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng00cDm8GVdR1_aLHNt:-Ng0IXER9uWwRviyZn6q:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.JobServer/appsettings.json#L22)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Remove queue, docker image and sharedfile.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.Serval.JobServer/appsettings.json` line 23 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng02NIJC-mtF31c93MQ:-Ng0D76916Dfv9Q1Q7rK:b-iup3du) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.JobServer/appsettings.json#L23)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Actually, it will throw an exception when making the periodic timer: https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer.-ctor?view=net-7.0
</blockquote></details>

This disables the `ClearMLMonitorService` on the job server. I put in a check for a zero TimeSpan. There is no need for it to run on both the engine server and the job server.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs` line 49 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng03mv_1LgKl0gioax0:-Ng0p6yMEvuheeIvmCeD:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs#L49)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There should be a test to delete an engine after a build has started.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-05 23:53 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 224 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1FXnG1hVMYH3vNRy7:-Ng1FXnG1hVMYH3vNRy8:bq32dmv) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L224)):*
> ```Smalltalk
>                 o.AddRepository<TranslationEngine>(
>                     "translation_engines",
>                     mapSetup: m => m.SetIgnoreExtraElements(true),
> ```

If I am correct, this should allow it to not crash with upgrading - though it will still remove all builds...


<!-- Sent from Reviewable.io -->

2023-10-05 23:55 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 151 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1G4feB7mm2X56ujvB:-Ng1G4feB7mm2X56ujvC:b-83y42m) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L151)):*
> ```Smalltalk
>         );
>         if (buildId is not null && jobState is BuildJobState.None)
>             await _platformService.BuildCanceledAsync(buildId, CancellationToken.None);
> ```

I am confused why it is broken up.  Would we ever cancel a build job instead of a build?  What does cancelling a build do over and above just cancelling the job?


<!-- Sent from Reviewable.io -->

2023-10-06 00:00 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 39 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1HJch1YToooUKF-LW:-Ng1HJciB3j4_IrQKmxA:bpp9sji) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L39)):*
> ```Smalltalk
>     public TranslationEngineType Type => TranslationEngineType.SmtTransfer;
> 
>     public async Task CreateAsync(
> ```

Now CreateAsync is showing as not covered by tests - weird: https://app.codecov.io/gh/sillsdev/machine/blob/refactor-clearml-job/src%2FSIL.Machine.AspNetCore%2FServices%2FSmtTransferEngineService.cs


<!-- Sent from Reviewable.io -->

2023-10-06 00:08 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 197 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1IUj0AbOEK9GZ4Afx:-Ng1IUj0AbOEK9GZ4Afy:borg5gk) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L197)):*
> ```Smalltalk
>         await using (await @lock.WriterLockAsync(cancellationToken: cancellationToken))
>         {
>             await CancelBuildJobAsync(engineId, cancellationToken);
> ```

Ok the same question for breaking out the cancel build and cancel build job.  The only difference is the lock and updating the state?  Why?  Why would I want to call one or the other?


<!-- Sent from Reviewable.io -->

2023-10-06 00:10 UTC, johnml1135 commented
*[`src/SIL.Machine.Serval.JobServer/appsettings.json` line 23 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng02NIJC-mtF31c93MQ:-Ng1JMl54IUrohfbZEFL:beq7rex) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.Serval.JobServer/appsettings.json#L23)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This disables the `ClearMLMonitorService` on the job server. I put in a check for a zero TimeSpan. There is no need for it to run on both the engine server and the job server.
</blockquote></details>

Can we have a parameter "enable polling" defaulted to false and instead place this on the engine server?  I believe that would be clearer.


<!-- Sent from Reviewable.io -->

2023-10-06 00:11 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs` line 49 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng03mv_1LgKl0gioax0:-Ng1JhCVCjnMn_d8S-h7:bm07088) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs#L49)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry to be finicky - can the test be called DeleteWhileBuildingAsync or similar?


<!-- Sent from Reviewable.io -->

2023-10-06 00:12 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 98 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1K4aw8VjvoeTBQB0N:-Ng1K4aw8VjvoeTBQB0O:ba2r62g) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L98)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task DeleteAsync()
> ```

DeleteWhileBuildingAsync?


<!-- Sent from Reviewable.io -->

2023-10-06 00:14 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs` line 223 at r2](https://reviewable.io/reviews/sillsdev/machine/101#-Ng-wYIW-_cJn_Aar3Pw:-Ng1KY5o8QPpntsPEItS:b4y9o3z) ([raw file](https://github.com/sillsdev/machine/blob/e3dbe61b636be6b1b20d630c5b8265bbd7fa5b8e/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs#L223)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

How did you get around this function (to be able to delete it)?


<!-- Sent from Reviewable.io -->

2023-10-06 00:16 UTC, johnml1135 reviewed
> Reviewed 9 of 9 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: all files reviewed, 7 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-06 16:30 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 151 at r3](https://reviewable.io/reviews/sillsdev/machine/101#-Ng1G4feB7mm2X56ujvB:-Ng4okHj0ux-SN__FCaa:b-8617my) ([raw file](https://github.com/sillsdev/machine/blob/e2ab7116f4b8beffc006ed2885d2e9bdff2e8a92/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L151)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This private method allows me to reuse the same code in the `CancelBuildAsync` and `DeleteAsync` methods.
</blockquote></details>

Ah, one is private, one is public.  I see.


<!-- Sent from Reviewable.io -->

2023-10-06 16:30 UTC, johnml1135 approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-06 16:37 UTC, johnml1135 commented
Some failing builds - https://github.com/sillsdev/machine/actions/runs/6434169750/job/17472827308.  We should really run e2e on pull requests.

2023-10-06 18:31 UTC, johnml1135 reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-06 19:52 UTC, ddaspit reviewed
I figured out why the E2E tests are failing. The appsettings changed and need to be updated in the Serval repo. In the future, it would be great if we could find a way to keep the appsettings for Machine in the Machine repo.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/101#-:-Ng5WjYG1K6gkKHTn38u:b-wzh8ek)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2023-10-06 19:53 UTC, merged