Update language code parsing
sillsdev/machine pull request #126
Opened 2023-10-30 19:00 UTC by johnml1135

Refactor for some edge cases and for cleaner understanding of what is going on.

2023-10-30 20:46 UTC, ddaspit requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/126)* status: all files reviewed, 8 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IQwbECUIFxLZB82Y:-Ni1IQwbECUIFxLZB82Z:b-1dc8sw) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L12)):*
> ```Smalltalk
>     private readonly Dictionary<string, string> _threeToTwo;
> 
>     private readonly Regex _langTagPattern;
> ```

This can be static.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1Ja-f2sc_FWvY8xz1:-Ni1Ja-f2sc_FWvY8xz2:b-1dc8sw) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L26)):*
> ```Smalltalk
>     }
> 
>     private Dictionary<string, string> InitializeDefaultScripts()
> ```

This can be static.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IGOwBRTgl5pSHIbD:-Ni1IGOxEWh2zNfZ0zGV:b-i8o22d) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L82)):*
> ```Smalltalk
>         if (!langTagMatch.Success)
>             return languageTag;
>         string parsed_language = langTagMatch.Groups["language"].Value;
> ```

Use camel case for variable names.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 90 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1HeGh0Iu_3OQ0UbJy:-Ni1HeGh0Iu_3OQ0UbJz:b-d25yzy) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L90)):*
> ```Smalltalk
> 
>         // If they gave us the ISO code, revert it to the 2 character code
>         if (_threeToTwo.ContainsKey(language_subtag))
> ```

SIL.WritingSystems already has a method for this purpose. It is called `StandardSubtags.TryGetLanguageFromIso3Code`.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 94 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1I4NdD3mtWiCzY-Y_:-Ni1I4NdD3mtWiCzY-Ya:b-dcwo3f) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L94)):*
> ```Smalltalk
> 
>         // There are a few extra conversions not in SIL Writing Systems that we need to handle
>         if (StandardLanguages.ContainsKey(language_subtag))
> ```

You should use `TryGetValue`. It saves a lookup and is more idiomatic C#.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1J5Fu6W50u_xP_DvX:-Ni1J5Fu6W50u_xP_DvY:b-8orhb3) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L97)):*
> ```Smalltalk
>             language_subtag = StandardLanguages[language_subtag];
> 
>         if (StandardSubtags.RegisteredLanguages.Contains(language_subtag))
> ```

Use `TryGet` here.
___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IeOTAjpMgIl3T0L0:-Ni1IeOTAjpMgIl3T0L1:bik6vdg) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L103)):*
> ```Smalltalk
>         Group scriptGroup = langTagMatch.Groups["script"];
>         string? script = null;
>         if (_defaultScripts.ContainsKey(language_subtag))
> ```

I would reverse these three `if` statements and use `else if` instead. It will save unnecessary lookups. Also use `TryGetVaue`.
___
*[`tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs` line 93 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1JrrIDn6xRJt_4f-7:-Ni1JrrIDn6xRJt_4f-8:b-q4jng9) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs#L93)):*
> ```Smalltalk
> 
>     [Test]
>     public void ConvertToFlores200Code_English()
> ```

I would rename this test. It isn't specific to English. It is really testing an invalid language tag where the ISO 639-3 code is used instead of the ISO 639-1 code.


<!-- Sent from Reviewable.io -->

2023-10-30 20:57 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IQwbECUIFxLZB82Y:-Ni1N2JP1mvQKwlOrIv5:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be static.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 20:58 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1Ja-f2sc_FWvY8xz1:-Ni1NGqoDDDPLjufTrqO:bivk580) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be static.
</blockquote></details>

Wouldn't you need to `Sldr.InitializeLanguageTags();` first?


<!-- Sent from Reviewable.io -->

2023-10-30 20:58 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IGOwBRTgl5pSHIbD:-Ni1NSCU7lnh7MDNMF-B:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Use camel case for variable names.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:03 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 90 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1HeGh0Iu_3OQ0UbJy:-Ni1OUSg2EKobuZdWFKh:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L90)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

SIL.WritingSystems already has a method for this purpose. It is called `StandardSubtags.TryGetLanguageFromIso3Code`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:04 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 94 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1I4NdD3mtWiCzY-Y_:-Ni1OpL56ZoMdZAKe_cB:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L94)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should use `TryGetValue`. It saves a lookup and is more idiomatic C#.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:06 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1J5Fu6W50u_xP_DvX:-Ni1PAWn-QhrweCLOItz:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L97)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Use `TryGet` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:07 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 103 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1IeOTAjpMgIl3T0L0:-Ni1PRDJA_vi_L1uyyQj:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L103)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would reverse these three `if` statements and use `else if` instead. It will save unnecessary lookups. Also use `TryGetVaue`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:17 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs` line 93 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1JrrIDn6xRJt_4f-7:-Ni1RcAt5Zquk5AvcQHZ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/tests/SIL.Machine.AspNetCore.Tests/Services/LanguageTagServiceTests.cs#L93)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this test. It isn't specific to English. It is really testing an invalid language tag where the ISO 639-3 code is used instead of the ISO 639-1 code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 21:52 UTC, ddaspit reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/126)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1Ja-f2sc_FWvY8xz1:-Ni1Y7IOBOWQJBP1BZ_T:b-5j0387) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Wouldn't you need to `Sldr.InitializeLanguageTags();` first?
</blockquote></details>

It will still be called first. Making the method static just means that the method is associated with the class instead of an instance. In any case, I would move `Sldr.InitializeLanguageTags();` inside `InitializeDefaultScripts`.


<!-- Sent from Reviewable.io -->

2023-10-30 21:53 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/126)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1ZkU6CJATvu-E0KEf:-Ni1ZkU6CJATvu-E0KEg:b9fzbvw) ([raw file](https://github.com/sillsdev/machine/blob/dc4944ccafa116c70772ee002bec719a2de3a97c/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L10)):*
> ```Smalltalk
>     private readonly Dictionary<string, string> _defaultScripts;
> 
>     private static readonly Regex _langTagPattern = new Regex(
> ```

I would rename this to `LangTagPattern`, since it is now a constant.


<!-- Sent from Reviewable.io -->

2023-10-31 11:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 10 at r2](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1ZkU6CJATvu-E0KEf:-Ni4Yz8c0KeLMyrBY_j7:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/dc4944ccafa116c70772ee002bec719a2de3a97c/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `LangTagPattern`, since it is now a constant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-31 11:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs` line 26 at r1](https://reviewable.io/reviews/sillsdev/machine/126#-Ni1Ja-f2sc_FWvY8xz1:-Ni4Z2TY1yY22-vs0hbJ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/acb60b1a5f86e114162f57e879f93701a2f33c83/src/SIL.Machine.AspNetCore/Services/LanguageTagService.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It will still be called first. Making the method static just means that the method is associated with the class instead of an instance. In any case, I would move `Sldr.InitializeLanguageTags();` inside `InitializeDefaultScripts`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-31 21:23 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/126#-:-Ni6bZtwDwtTixufGRoY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2023-11-01 12:14 UTC, merged