Smt on clearml
sillsdev/machine pull request #200
Opened 2024-05-17 20:03 UTC by johnml1135

There are a still a bug or two to work out - but it should be good enough to review.  There will likely be more churn in review at this point than from bugs.

2024-05-17 21:52 UTC, ddaspit requested changes
This is looking good.

> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200#-:-Ny7XeHOCGaKyyTjwevn:bjwdyzf)* status: all files reviewed, 19 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Tw24CwnU0MhJULM0:-Ny7Tw2574Hyg7tDbrez:bojjexb) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs#L3)):*
> ```Smalltalk
> namespace SIL.Machine.AspNetCore.Configuration;
> 
> public class ClearMLBuildJobOptions
> ```

I would rename this. The `Options` suffix usually indicates that it is a config model that can be injected into a service. Maybe `ClearMLBuildQueue`.
___
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7AUxDBs_yJSpGOXL8:-Ny7AUxEB7fEooFi7Rhv:b-16nsz8) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs#L5)):*
> ```Smalltalk
> public class ClearMLBuildJobOptions
> {
>     public const string Key = "ClearMLBuildJob";
> ```

I don't think this key is necessary.
___
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLEngineTypeOptions.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7FVgb6cbofwpVNTg3:-Ny7FVgc6VW11fJwUuHH:b5sc13u) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLEngineTypeOptions.cs#L3)):*
> ```Smalltalk
> namespace SIL.Machine.AspNetCore.Configuration;
> 
> public class ClearMLEngineTypeOptions
> ```

Is this class used anywhere?
___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 361 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7BxaSESQrMsH9CUGb:-Ny7BxaSESQrMsH9CUGc:bn38yik) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L361)):*
> ```Smalltalk
>     public static IMachineBuilder AddBuildJobService(this IMachineBuilder builder)
>     {
>         if (builder.Configuration is not null)
> ```

This method should support with and without the `Configuration` property being set, just like it did before.
___
*[`src/SIL.Machine.AspNetCore/Models/Build.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7CJJN0Svq8rlv712g:-Ny7CJJN0Svq8rlv712h:b-q1lnn0) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Models/Build.cs#L11)):*
> ```Smalltalk
> }
> 
> public enum JobRunnerType
> ```

I would rename this to `BuildJobRunnerType` to make it consistent with the other enums.
___
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7FzfF-uAtGeX3neGO:-Ny7FzfF-uAtGeX3neGP:bw76cww) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
> ```Smalltalk
>     public int Revision { get; set; } = 1;
>     public required string EngineId { get; init; }
>     public required TranslationEngineType Type { get; init; } = TranslationEngineType.Nmt;
> ```

A default value isn't necessary.
___
*[`src/SIL.Machine.AspNetCore/Services/BuildJobService.cs` line 81 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7DEh07_fR_ERYoQma:-Ny7DEh07_fR_ERYoQmb:b-4l93c6) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/BuildJobService.cs#L81)):*
> ```Smalltalk
>             return false;
>         }
>         TranslationEngine engine = (await _engines.GetAsync(e => e.EngineId == engineId, cancellationToken))!;
> ```

You should update the preceding `ExistsAsync` call to `GetAsync`, so you don't have to hit the database twice.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7ER_CCwBmtdiZTIg-:-Ny7ER_CCwBmtdiZTIg0:b-tjhufc) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L11)):*
> ```Smalltalk
>     private readonly HttpClient _httpClient = httpClientFactory.CreateClient("ClearML-NoRetry");
>     private readonly IClearMLAuthenticationService _clearMLAuthenticationService = clearMLAuthenticationService;
>     private readonly IReadOnlyList<string> _queuesMonitored = buildJobOptions
> ```

It would probably be easier just to make this a hash set.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7E59oEJEmAzPojXnH:-Ny7E59oEJEmAzPojXnI:b-u86siu) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L28)):*
> ```Smalltalk
>             if (!await PingAsync(cancellationToken))
>                 return HealthCheckResult.Unhealthy("ClearML is unresponsive");
>             IEnumerable<string> queuesWithoutWorkers = await QueuesWithoutWorkers(cancellationToken);
> ```

I would return a `IReadOnlySet` and check the `Count`. LINQ functions can often be inefficient if the underlying type is a collection.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7S3ar8-CbPTS0xU1S:-Ny7S3ar8-CbPTS0xU1T:b7bfoo5) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L34)):*
> ```Smalltalk
>         buildJobOptions.CurrentValue.ClearML.ToDictionary(x => x.TranslationEngineType, x => x.Queue);
> 
>     public IDictionary<TranslationEngineType, int> QueueSizePerEngineType { get; private set; } =
> ```

I would add a separate interface to expose the queue sizes. Maybe something like `IClearMLQueueService`. The dictionary could have issues with race conditions. I would use `ConcurrentDictionary` and just expose the queue size using a method `GetQueueSize`.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qlg_AIIRnIiRbta1:-Ny7Qlg_AIIRnIiRbta2:b-w0008c) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L66)):*
> ```Smalltalk
>                     .ToDictionary(t => t.Id);
>                 // add new keys to dictionary
>                 tasksPerEngineType.ToList().ForEach(x => tasks.TryAdd(x.Key, x.Value));
> ```

The `ToList()` isn't necessary.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qo_C2hqE5VrM-QBb:-Ny7Qo_DB_hlziMY2dx0:b-w0008c) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L74)):*
> ```Smalltalk
>                     .ToDictionary(e => e.Task.Name, e => e.Position);
>                 // add new keys to dictionary
>                 queuePositionsPerEngineType.ToList().ForEach(x => queuePositions.TryAdd(x.Key, x.Value));
> ```

The `ToList()` isn't necessary.
___
*[`src/SIL.Machine.AspNetCore/Services/PostprocessBuildJob.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7HTIC9CS5Gz-s12vJ:-Ny7HTIC9CS5Gz-s12vK:b-w6fyfk) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/ [...]

2024-05-20 18:56 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Tw24CwnU0MhJULM0:-NyMMBCi9Tbu78bpOs4c:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this. The `Options` suffix usually indicates that it is a config model that can be injected into a service. Maybe `ClearMLBuildQueue`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 18:56 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7AUxDBs_yJSpGOXL8:-NyMMCF-7wrbA8Oru6U9:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLBuildJobOptions.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this key is necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 18:57 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/ClearMLEngineTypeOptions.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7FVgb6cbofwpVNTg3:-NyMMIAF5hk9R4vGqU6v:b-dmcqrw) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/ClearMLEngineTypeOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is this class used anywhere?
</blockquote></details>

Nice catch - was made by accident.


<!-- Sent from Reviewable.io -->

2024-05-20 19:02 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 361 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7BxaSESQrMsH9CUGb:-NyMNX_O0oS5MTFdEppE:b-7mzbda) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L361)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This method should support with and without the `Configuration` property being set, just like it did before.
</blockquote></details>

I believe this is the only change needed.


<!-- Sent from Reviewable.io -->

2024-05-20 19:03 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/Build.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7CJJN0Svq8rlv712g:-NyMNoqW3rJ6tNsKf--h:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Models/Build.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `BuildJobRunnerType` to make it consistent with the other enums.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 19:23 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/BuildJobService.cs` line 81 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7DEh07_fR_ERYoQma:-NyMSKh3-9L863oenvpu:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/BuildJobService.cs#L81)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should update the preceding `ExistsAsync` call to `GetAsync`, so you don't have to hit the database twice.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 19:25 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 11 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7ER_CCwBmtdiZTIg-:-NyMSnUODtdMVg7wfoAZ:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would probably be easier just to make this a hash set.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 19:29 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 28 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7E59oEJEmAzPojXnH:-NyMTeYGDNz249Rp37SI:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L28)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would return a `IReadOnlySet` and check the `Count`. LINQ functions can often be inefficient if the underlying type is a collection.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 19:41 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7S3ar8-CbPTS0xU1S:-NyMWU4DA5vnU4U96Dne:b1gw39p) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would add a separate interface to expose the queue sizes. Maybe something like `IClearMLQueueService`. The dictionary could have issues with race conditions. I would use `ConcurrentDictionary` and just expose the queue size using a method `GetQueueSize`.
</blockquote></details>

I think this is what you are looking for.


<!-- Sent from Reviewable.io -->

2024-05-20 19:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qlg_AIIRnIiRbta1:-NyMXrNB6rjk8rXVSyOf:b-duunzg) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L66)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `ToList()` isn't necessary.
</blockquote></details>

It did need it - but I refactored to be a little clearer.  What do you think?


<!-- Sent from Reviewable.io -->

2024-05-20 19:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qo_C2hqE5VrM-QBb:-NyMXzIA-fxsHPgyunNh:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L74)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `ToList()` isn't necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 20:46 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PostprocessBuildJob.cs` line 14 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7HTIC9CS5Gz-s12vJ:-NyMkQEt3-vZ6Gb7PZhX:b-xo2ekq) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/PostprocessBuildJob.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would just make this a protected property. You could also pass in the value for this to the constructor, so it doesn't have to be overridden.
</blockquote></details>

Ok - removed the primary constructors.


<!-- Sent from Reviewable.io -->

2024-05-20 20:47 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7HmqmEguMqOK4AA46:-NyMkU9lE-vEmRZWybqu:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make these protected properties. You could also pass in the values for this to the constructor, so they don't have to be overridden.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 20:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 85 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7JRezBIILv3vhT3iF:-NyMklDZ5k28QLn9ZeJ1:bne1mke) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L85)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think it would be clearer to pass `JobRunnerType.ClearML`.
</blockquote></details>

This can be overridden to do hangfire for SMT for testing.


<!-- Sent from Reviewable.io -->

2024-05-20 20:56 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 31 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7MiMn3I0ppI2C_KF3:-NyMmXKqCvA7XovBP4qz:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L31)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

All of the following should happen in single lock:
- The model updated on disk.
- The model trained on new segments.
- The local state updated.
- The Serval state updated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 21:01 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 80 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7MS0BAhM-pn8bahyf:-NyMns-N4jdUP7dn7qQN:b4oyx07) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L80)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `SmtTransferEngineStateService` was designed for the live inferencing in the engine server. I wouldn't use it here. You can just load the model directly and train the segments.
</blockquote></details>

How do I load it directly?


<!-- Sent from Reviewable.io -->

2024-05-20 21:02 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 126 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7UyYj8IxLWG9wUybG:-NyMnuey2Q3V-5gXhYFj:b-45hh5n) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the delay for? This usually indicates that the test might not be deterministic and therefore flaky.
</blockquote></details>

It was on windows...


<!-- Sent from Reviewable.io -->

2024-05-20 21:02 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 274 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7VaEK7xL8UbFP0duM:-NyMnxgSC4XFz-PQeLoa:b4t645i) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L274)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is best to avoid hitting the file system in a unit test. What is this for?
</blockquote></details>

I believe we could not use a memory stream - I could be wrong...


<!-- Sent from Reviewable.io -->

2024-05-21 17:30 UTC, ddaspit reviewed
> Reviewed 1 of 4 files at r2, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 18 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 361 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7BxaSESQrMsH9CUGb:-NyR9L1aA3cGwFJ1_wnR:b-il2sz4) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L361)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I believe this is the only change needed.
</blockquote></details>

This should be what we want:

```
    public static IMachineBuilder AddBuildJobService(this IMachineBuilder builder, string? smtTransferEngineDir = null)
    {
        builder.Services.AddScoped<IBuildJobService, BuildJobService>();

        builder.Services.AddScoped<IBuildJobRunner, ClearMLBuildJobRunner>();
        builder.Services.AddScoped<IClearMLBuildJobFactory, NmtClearMLBuildJobFactory>();
        builder.Services.AddScoped<IClearMLBuildJobFactory, SmtTransferClearMLBuildJobFactory>();
        builder.Services.AddSingleton<IClearMLQueueService, ClearMLMonitorService>();
        builder.Services.AddHostedService(p => p.GetRequiredService<ClearMLMonitorService>());

        builder.Services.AddScoped<IBuildJobRunner, HangfireBuildJobRunner>();
        builder.Services.AddScoped<IHangfireBuildJobFactory, NmtHangfireBuildJobFactory>();
        builder.Services.AddScoped<IHangfireBuildJobFactory, SmtTransferHangfireBuildJobFactory>();

        if (smtTransferEngineDir is null)
        {
            var smtTransferEngineOptions = new SmtTransferEngineOptions();
            builder.Configuration?.GetSection(SmtTransferEngineOptions.Key).Bind(smtTransferEngineOptions);
            smtTransferEngineDir = smtTransferEngineOptions.EnginesDir;
        }
        string? driveLetter = Path.GetPathRoot(smtTransferEngineDir)?[..1];
        if (driveLetter is null)
            throw new InvalidOperationException("SMT Engine directory is required");
        // add health check for disk storage capacity
        builder
            .Services.AddHealthChecks()
            .AddDiskStorageHealthCheck(
                x => x.AddDrive(driveLetter, 1_000), // 1GB
                "SMT Engine Storage Capacity",
                HealthStatus.Degraded
            );

        return builder;
    }
```
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 15 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQy_R-Ax_K-1gGfgax:-NyQy_R-Ax_K-1gGfgay:b46qs44) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L15)):*
> ```Smalltalk
>     private readonly ISet<string> _queuesMonitored = buildJobOptions
>         .CurrentValue.ClearML.Select(x => x.Queue)
>         .Distinct()
> ```

The `Distinct` call is unnecessary.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 82 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQyriQ2WKSm8hABY9U:-NyQyriQ2WKSm8hABY9V:b-xo8h2c) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L82)):*
> ```Smalltalk
>     public async Task<IReadOnlySet<string>> QueuesWithoutWorkers(CancellationToken cancellationToken = default)
>     {
>         ISet<string> queuesWithoutWorkers = _queuesMonitored.ToHashSet();
> ```

If you change the type to `HashSet<string>`, then you don't need to convert to an `ImmutableHashSet` before returning. `HashSet` implements the `IReadOnlySet` interface.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7S3ar8-CbPTS0xU1S:-NyQzKymE7EELiaBa3-i:btjw0qs) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L34)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think this is what you are looking for.
</blockquote></details>

I suggested exposing `GetQueueSize` instead of the dictionary, because we don't want to expose a mutable dictionary. `GetQueueSize` is also a simpler API.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qlg_AIIRnIiRbta1:-NyQzycZ4BgeLsqVY04W:beumq6c) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L66)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It did need it - but I refactored to be a little clearer.  What do you think?
</blockquote></details>

It isn't safe to iterate over a collection while mutating it. I think the following would work:

```
foreach (KeyValuePair<string, ClearMLTask> kvp in tasksPerEngineType)
    tasks.TryAdd(kvp.Key, kvp.Value);
```
___
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 29 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR0tE6-QBqhdmgO-E_:-NyR0tE6-QBqhdmgO-Ea:but7zcv) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L29)):*
> ```Smalltalk
>         // Get all engine ids from the database
>         IReadOnlyList<TranslationEngine>? allEngines = await _engines.GetAllAsync(cancellationToken: cancellationToken);
>         IEnumerable<string> validFilenames = allEngines
> ```

It would probably be good to rename these variables to indicate that these are for NMT models. Maybe `validNmtModelFilenames`.
___
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 38 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR0lbf0Wf6r5IsGH60:-NyR0lbf0Wf6r5IsGH61:bxsoym7) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L38)):*
> ```Smalltalk
>             .Select(e => NmtEngineService.GetModelPath(e.EngineId, e.BuildRevision + 1));
>         // Add SMT engines
>         IEnumerable<string> validSMTModels = allEngines
> ```

I don't think this is being used anywhere.
___
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 172 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR6K-k9uvZjIUm7nkM:-NyR6K-k9uvZjIUm7nkN:b5mn5wz) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L172)):*
> ```Smalltalk
>     }
> 
>     public Task<int> GetQueueSizeAsync(CancellationToken cancellationToken = default)
> ```

This method doesn't need to be async anymore.
___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7HmqmEguMqOK4AA46:-NyR6Ntd8WwDoxWX31rM:b-o54a7t) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L13)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

These properties aren't used outside of this class and the classes that inherit from it, so the properties don't need to be public.
___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7Jb8BV3RxKhZiExw:-NyR7Jb8BV3RxKhZiExx:bl95wat) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ [...]

2024-05-21 18:50 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs` line 361 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7BxaSESQrMsH9CUGb:-NyRUU0yCbUv-ooS--9c:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Configuration/IMachineBuilderExtensions.cs#L361)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be what we want:

```
    public static IMachineBuilder AddBuildJobService(this IMachineBuilder builder, string? smtTransferEngineDir = null)
    {
        builder.Services.AddScoped<IBuildJobService, BuildJobService>();

        builder.Services.AddScoped<IBuildJobRunner, ClearMLBuildJobRunner>();
        builder.Services.AddScoped<IClearMLBuildJobFactory, NmtClearMLBuildJobFactory>();
        builder.Services.AddScoped<IClearMLBuildJobFactory, SmtTransferClearMLBuildJobFactory>();
        builder.Services.AddSingleton<IClearMLQueueService, ClearMLMonitorService>();
        builder.Services.AddHostedService(p => p.GetRequiredService<ClearMLMonitorService>());

        builder.Services.AddScoped<IBuildJobRunner, HangfireBuildJobRunner>();
        builder.Services.AddScoped<IHangfireBuildJobFactory, NmtHangfireBuildJobFactory>();
        builder.Services.AddScoped<IHangfireBuildJobFactory, SmtTransferHangfireBuildJobFactory>();

        if (smtTransferEngineDir is null)
        {
            var smtTransferEngineOptions = new SmtTransferEngineOptions();
            builder.Configuration?.GetSection(SmtTransferEngineOptions.Key).Bind(smtTransferEngineOptions);
            smtTransferEngineDir = smtTransferEngineOptions.EnginesDir;
        }
        string? driveLetter = Path.GetPathRoot(smtTransferEngineDir)?[..1];
        if (driveLetter is null)
            throw new InvalidOperationException("SMT Engine directory is required");
        // add health check for disk storage capacity
        builder
            .Services.AddHealthChecks()
            .AddDiskStorageHealthCheck(
                x => x.AddDrive(driveLetter, 1_000), // 1GB
                "SMT Engine Storage Capacity",
                HealthStatus.Degraded
            );

        return builder;
    }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 18:53 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 82 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQyriQ2WKSm8hABY9U:-NyRUzT67u9urbAiC_oP:bksbze0) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If you change the type to `HashSet<string>`, then you don't need to convert to an `ImmutableHashSet` before returning. `HashSet` implements the `IReadOnlySet` interface.
</blockquote></details>

explicit cast...


<!-- Sent from Reviewable.io -->

2024-05-21 18:56 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7S3ar8-CbPTS0xU1S:-NyRVpeU-XDGGHgSUMbg:b-8fqg3a) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I suggested exposing `GetQueueSize` instead of the dictionary, because we don't want to expose a mutable dictionary. `GetQueueSize` is also a simpler API.
</blockquote></details>

Makes sense - that would be a more standard interface.


<!-- Sent from Reviewable.io -->

2024-05-21 18:59 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 66 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7Qlg_AIIRnIiRbta1:-NyRWP1d4vtat17EdKiF:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L66)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It isn't safe to iterate over a collection while mutating it. I think the following would work:

```
foreach (KeyValuePair<string, ClearMLTask> kvp in tasksPerEngineType)
    tasks.TryAdd(kvp.Key, kvp.Value);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:00 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 15 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQy_R-Ax_K-1gGfgax:-NyRWfFm5LicCX4pAZWU:b-thrvtb) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `Distinct` call is unnecessary.
</blockquote></details>

Hashset already makes it distinct...


<!-- Sent from Reviewable.io -->

2024-05-21 19:02 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 29 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR0tE6-QBqhdmgO-E_:-NyRX6nh6QR5gQULRsCN:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would probably be good to rename these variables to indicate that these are for NMT models. Maybe `validNmtModelFilenames`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:02 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 38 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR0lbf0Wf6r5IsGH60:-NyRX8-14WISGI75aTyM:bt2vr1b) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L38)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this is being used anywhere.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-05-21 19:04 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs` line 172 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR6K-k9uvZjIUm7nkM:-NyRXghV9oEE3Zuurgkq:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/NmtEngineService.cs#L172)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This method doesn't need to be async anymore.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:15 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 13 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7HmqmEguMqOK4AA46:-NyR_4Ni2vJp0eYymRJ7:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These properties aren't used outside of this class and the classes that inherit from it, so the properties don't need to be public.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:16 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 181 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR2SjP4e9E5ofbB9a-:-NyR_M5BA_bQTCs_kR34:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L181)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should skip over this loop if pretranslations aren't enabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:25 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 54 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7w1V7_SQtpBVow8w:-NyRbHKi0PjY9XXM0e2h:b-l1masz) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L54)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

File system access should be abstracted behind an interface to make it easier to write unit tests. In this case, the `ISmtModelFactory` interface would probably be appropriate. It is the interface that is currently used to abstract file access to SMT models.
</blockquote></details>

I don't fully understand how I would do this.


<!-- Sent from Reviewable.io -->

2024-05-21 19:29 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs` line 198 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR47wr8X6UdW4TrVMw:-NyRcCti2LNY22czAG_x:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/tests/SIL.Machine.AspNetCore.Tests/Services/NmtEngineServiceTests.cs#L198)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to rename this property.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:29 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 356 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR4Kko8Wr1sJHMHntH:-NyRcK8804wdaKLDKUFU:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L356)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to rename this property.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 19:55 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 80 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7MS0BAhM-pn8bahyf:-NyRiF6R0uHOXHJkPVy0:b1gw39p) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L80)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can look at the original `SmtTransferBuildJob` class to get an idea.
</blockquote></details>

I think this is what you are looking for.


<!-- Sent from Reviewable.io -->

2024-05-21 20:05 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 54 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7w1V7_SQtpBVow8w:-NyRkdwlE3vca3Ax6Dkn:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L54)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I don't fully understand how I would do this.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-22 14:31 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 126 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7UyYj8IxLWG9wUybG:-NyVheNo-ZbJCmaU_x0_:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should be able to figure out how to get the test to work without the delay.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 14:47 UTC, johnml1135 commented
*[`tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs` line 274 at r1](https://reviewable.io/reviews/sillsdev/machine/200#-Ny7VaEK7xL8UbFP0duM:-NyVlLHO2NAtOChRalEz:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e0201347b60608eb5220d595712edf2c77532370/tests/SIL.Machine.AspNetCore.Tests/Services/SmtTransferEngineServiceTests.cs#L274)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my [comment](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7w1V7_SQtpBVow8w) above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 16:17 UTC, ddaspit reviewed
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 82 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQyriQ2WKSm8hABY9U:-NyVnKDu4D_EFi3FT7bm:b-z3mu5y) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L82)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

explicit cast...
</blockquote></details>

You should avoid explicit casting as much as possible. The cast isn't necessary if you change the type to `HashSet<string>`.
___
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 39 at r4](https://reviewable.io/reviews/sillsdev/machine/200#-NyVoQSTDGZMHOvKGSDe:-NyVoQSTDGZMHOvKGSDf:b-rxbith) ([raw file](https://github.com/sillsdev/machine/blob/b6ac585e80dadcc87badf0405c4f91e809b3d002/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L39)):*
> ```Smalltalk
> 
>         // Add SMT engines
>         IEnumerable<string> validSMTModels = allEngines
> ```

The variable should be `validSmtModels`. For acronyms longer than 2 characters, only the first character is capitalized. 
___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7Jb8BV3RxKhZiExw:-NyW384nCxTQAHEINPeb:bqdv7iz) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think these changes will work.
</blockquote></details>

The standard practice when you expose the implementation of a class for testing purposes is to make the property/method/field `internal`. This clearly indicates that it isn't part of the public API and should not be used by normal callers.


<!-- Sent from Reviewable.io -->

2024-05-22 19:46 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs` line 82 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyQyriQ2WKSm8hABY9U:-NyWpoTnAlVyYgr1rWTf:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/ClearMLHealthCheck.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should avoid explicit casting as much as possible. The cast isn't necessary if you change the type to `HashSet<string>`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 19:46 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs` line 39 at r4](https://reviewable.io/reviews/sillsdev/machine/200#-NyVoQSTDGZMHOvKGSDe:-NyWptapALQ0dJJm4YeM:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/b6ac585e80dadcc87badf0405c4f91e809b3d002/src/SIL.Machine.AspNetCore/Services/ModelCleanupService.cs#L39)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The variable should be `validSmtModels`. For acronyms longer than 2 characters, only the first character is capitalized.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 19:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7Jb8BV3RxKhZiExw:-NyWq2VrDTjwHJ0ssIi0:bbf60kw) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The standard practice when you expose the implementation of a class for testing purposes is to make the property/method/field `internal`. This clearly indicates that it isn't part of the public API and should not be used by normal callers.
</blockquote></details>

Ah, the things I don't know about C#...  how can I count they ways, as long as the count property is public because I am not part of the assembly.


<!-- Sent from Reviewable.io -->

2024-05-22 21:26 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 202 at r5](https://reviewable.io/reviews/sillsdev/machine/200#-NyXBKOJ5fUwiVBQ5uZO:-NyXBKOJ5fUwiVBQ5uZP:b-xahce6) ([raw file](https://github.com/sillsdev/machine/blob/52eba078af030501460eeec43c1791c7d6beb96c/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L202)):*
> ```Smalltalk
> 
>         pretranslateWriter.WriteEndArray();
>         await pretranslateWriter.FlushAsync(cancellationToken);
> ```

You don't need to flush the writer. It will be flushed when it is disposed.


<!-- Sent from Reviewable.io -->

2024-05-23 13:04 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 202 at r5](https://reviewable.io/reviews/sillsdev/machine/200#-NyXBKOJ5fUwiVBQ5uZO:-Ny_KTcJ4oz11aQ055Qd:b-i6rr7o) ([raw file](https://github.com/sillsdev/machine/blob/52eba078af030501460eeec43c1791c7d6beb96c/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L202)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You don't need to flush the writer. It will be flushed when it is disposed.
</blockquote></details>

It was flushed with Write, not WriteAsync.  With the now implemented Write, it should be ok.  Removed. 


<!-- Sent from Reviewable.io -->

2024-05-23 13:08 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPreprocessBuildJob.cs` line 18 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_YuA-Ay3GIlpQGOcM:-Ny_YuA0AALR2adrbzwO:bta10s8) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Services/SmtTransferPreprocessBuildJob.cs#L18)):*
> ```Smalltalk
>         EngineType = TranslationEngineType.SmtTransfer;
>         PretranslationEnabled = false;
>         TrainJobRunnerType = BuildJobRunnerType.Hangfire;
> ```

This is hard coded - it should be configurable through either build options (probably not) or environment variables.  Right now, with the python SMT so slow, the E2E tests will time out.  We need to either speed up the python code or run the SMT in hangfire for E2E testing.


<!-- Sent from Reviewable.io -->

2024-05-23 13:19 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs` line 13 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_afTo9ig4cPtutxkU:-Ny_afTo9ig4cPtutxkV:bm0ho9) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs#L13)):*
> ```Smalltalk
>         buildJobFactories.ToDictionary(f => f.EngineType);
> 
>     private readonly Dictionary<TranslationEngineType, ClearMLBuildQueue> _options =
> ```

An error when running E2E tests on docker-compose: 
```
machine-engine-cntr  |       System.ArgumentException: An item with the same key has already been added. Key: SmtTransfer
machine-engine-cntr  |          at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
machine-engine-cntr  |          at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
machine-engine-cntr  |          at SIL.Machine.AspNetCore.Services.ClearMLBuildJobRunner..ctor(IClearMLService clearMLService, IEnumerable`1 buildJobFactories, IOptionsMonitor`1 options) in /home/johnml1135/repos/machine/src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs:line 13
machine-engine-cntr  |          at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
machine-engine-cntr  |          at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
machine-engine-cntr  |          at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
machine-engine-cntr  |          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
machine-engine-cntr  |          at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
```


<!-- Sent from Reviewable.io -->

2024-05-23 14:32 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_rQPD8yBVOnoJx3u2:-Ny_rQPD8yBVOnoJx3u3:b-7pzp9z) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
> ```Smalltalk
>     public int Revision { get; set; } = 1;
>     public required string EngineId { get; init; }
>     public required TranslationEngineType Type { get; init; }
> ```

This may break because of database migration.  Current plan: 
* bring down machine
* delete all machine database entries
* Bring up the new machine 


<!-- Sent from Reviewable.io -->

2024-05-23 19:29 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 202 at r5](https://reviewable.io/reviews/sillsdev/machine/200#-NyXBKOJ5fUwiVBQ5uZO:-NyauSJw3Yy4vksOyjZA:b-kmnx26) ([raw file](https://github.com/sillsdev/machine/blob/52eba078af030501460eeec43c1791c7d6beb96c/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L202)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It was flushed with Write, not WriteAsync.  With the now implemented Write, it should be ok.  Removed.
</blockquote></details>

This is happening, because you aren't using `IAsyncDisposable.DisposeAsync()`. The correct way to fix this is to use `await using` when you create the stream and writer.
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 50 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-NyautGu4PhOGwYdDHzt:-NyautGu4PhOGwYdDHzu:b63qi9r) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L50)):*
> ```Smalltalk
> 
>     public override void Write(byte[] buffer, int offset, int count)
>     {
> ```

It is dangerous to call async methods from sync methods. We should revert these changes.


<!-- Sent from Reviewable.io -->

2024-06-04 19:17 UTC, ddaspit reviewed
> Reviewed 27 of 31 files at r7, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 7 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs` line 37 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZXpPqA8QrxMp2LfIC:-NzZXpPqA8QrxMp2LfID:bebosah) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs#L37)):*
> ```Smalltalk
> }
> 
> internal sealed class DictionaryStringStringConverter : JsonConverter<IReadOnlyDictionary<string, string>>
> ```

This should be moved to the `SIL.Machine.AspNetCore.Utils` namespace.
___
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 164 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZYaoED3MB6rJubkqU:-NzZYaoED3MB6rJubkqV:bc4rsk4) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L164)):*
> ```Smalltalk
>                                 engine.EngineId,
>                                 engine.CurrentBuild.BuildId,
>                                 (int)GetMetric(task, SummaryMetric, TrainCorpusSizeVariant),
> ```

We need to test that the train corpus size and confidence are correctly set in the Serval build.
___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 202 at r5](https://reviewable.io/reviews/sillsdev/machine/200#-NyXBKOJ5fUwiVBQ5uZO:-NyfOAur4EZxDdAgYrtT:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/52eba078af030501460eeec43c1791c7d6beb96c/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L202)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is happening, because you aren't using `IAsyncDisposable.DisposeAsync()`. The correct way to fix this is to use `await using` when you create the stream and writer.
</blockquote></details>

Done
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 50 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-NyautGu4PhOGwYdDHzt:-NyfQquv24oM4B4AkVbp:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L50)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is dangerous to call async methods from sync methods. We should revert these changes.
</blockquote></details>

Done
___
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 1 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZblty5JiT85oWl2o1:-NzZblty5JiT85oWl2o2:b-6ek0is) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L1)):*
> ```Smalltalk
> using CommunityToolkit.HighPerformance;
> ```

This should be moved to the global usings.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 25 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZcu1K-1xXKmz_l0jb:-NzZcu1K-1xXKmz_l0jc:b-fhvfln) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L25)):*
> ```Smalltalk
>         await using (
>             Stream engineStream = await SharedFileService.OpenReadAsync(
>                 $"builds/{buildId}/model.zip",
> ```

We need to figure out where to save the model on the S3 bucket. Right now, I believe that Machine.py is saving the model to the `models` directory. I don't know if this is the best place to save the model. The `models` directory is currently being used for downloading models. This is a different use case. Here we simply need to transfer the model from ClearML to the Machine engine. I think it would probably be better to save the model to the `builds` directory, which is what this code currently expects.
___
*[`src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs` line 72 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZf6VA1moZ0cIluaUX:-NzZf6VA1moZ0cIluaUY:b8yfg6j) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs#L72)):*
> ```Smalltalk
>         if (!Directory.Exists(engineDir))
>             Directory.CreateDirectory(engineDir);
>         ZipFile.ExtractToDirectory(source, engineDir, overwriteFiles: true);
> ```

Machine.py is now saving the model as `.tar.gz`. We need to update this code accordingly.
___
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPreprocessBuildJob.cs` line 18 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_YuA-Ay3GIlpQGOcM:-NzZfl6BCRlQvZTWJByP:bb6un1j) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Services/SmtTransferPreprocessBuildJob.cs#L18)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is hard coded - it should be configurable through either build options (probably not) or environment variables.  Right now, with the python SMT so slow, the E2E tests will time out.  We need to either speed up the python code or run the SMT in hangfire for E2E testing.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-07 20:25 UTC, ddaspit reviewed
> Reviewed 7 of 7 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 7 unresolved discussions (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-06-10 19:46 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs` line 37 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZXpPqA8QrxMp2LfIC:-O-2g4hz8xDGcUEid9ed:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Models/ClearMLTask.cs#L37)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be moved to the `SIL.Machine.AspNetCore.Utils` namespace.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 19:58 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs` line 164 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZYaoED3MB6rJubkqU:-O-2ibt0-rDF2U8fssbA:b-twiad0) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ClearMLMonitorService.cs#L164)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We need to test that the train corpus size and confidence are correctly set in the Serval build.
</blockquote></details>

Added to E2E test to verify corpus size and confidence.


<!-- Sent from Reviewable.io -->

2024-06-10 20:00 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs` line 1 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZblty5JiT85oWl2o1:-O-2jE-cBbjrrls-JiHt:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be moved to the global usings.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 20:02 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs` line 25 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZcu1K-1xXKmz_l0jb:-O-2jYRYC3GxAjvzOuVx:brz4j8g) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/SmtTransferPostprocessBuildJob.cs#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We need to figure out where to save the model on the S3 bucket. Right now, I believe that Machine.py is saving the model to the `models` directory. I don't know if this is the best place to save the model. The `models` directory is currently being used for downloading models. This is a different use case. Here we simply need to transfer the model from ClearML to the Machine engine. I think it would probably be better to save the model to the `builds` directory, which is what this code currently expects.
</blockquote></details>

I already moved it to the builds directory for both machine and machine.py.  I agree - I want the SMT model to auto-delete the same way the other build files auto-delete at the end of the build job.


<!-- Sent from Reviewable.io -->

2024-06-10 20:03 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs` line 72 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZf6VA1moZ0cIluaUX:-O-2jlX50cXaqgYDFjsB:b27czng) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs#L72)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Machine.py is now saving the model as `.tar.gz`. We need to update this code accordingly.
</blockquote></details>

I changed it back to .zip.  Dotnet handles .zip easier than tar.gz and python doesn't care.


<!-- Sent from Reviewable.io -->

2024-06-10 20:03 UTC, johnml1135 reviewed
> Reviewed 1 of 46 files at r1, 1 of 27 files at r3, 11 of 31 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: 59 of 66 files reviewed, 7 unresolved discussions (waiting on @ddaspit)

___
*[`src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs` line 7 at r3](https://reviewable.io/reviews/sillsdev/machine/200#-NyR7Jb8BV3RxKhZiExw:-NyWqHAwC9Rb5CGdY7lU:bccejyb) ([raw file](https://github.com/sillsdev/machine/blob/a7ecd6478f4bcb0a51877066453bf58d7ad10bf9/src/SIL.Machine.AspNetCore/Services/PreprocessBuildJob.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ah, the things I don't know about C#...  how can I count they ways, as long as the count property is public because I am not part of the assembly.
</blockquote></details>

Actually, I do want it to be public - 


<!-- Sent from Reviewable.io -->

2024-06-10 20:48 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs` line 72 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZf6VA1moZ0cIluaUX:-O-2u5DZ2RjE5kGL_FvQ:bnva4p9) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I changed it back to .zip.  Dotnet handles .zip easier than tar.gz and python doesn't care.
</blockquote></details>

Correction - brought back to gzip - just needed to use a new dotnet library to make the code of sensible size.


<!-- Sent from Reviewable.io -->

2024-06-10 20:53 UTC, ddaspit reviewed
> Reviewed 7 of 7 files at r13, 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: 59 of 67 files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_rQPD8yBVOnoJx3u2:-O-2qOc9BcpiR2lP2wdd:b-evh68h) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This may break because of database migration.  Current plan: 
* bring down machine
* delete all machine database entries
* Bring up the new machine
</blockquote></details>

I don't think that deleting the Machine database is an option. It would break all of the existing Serval engines. I believe that this is the only breaking DB change. I actually think that we might be able to get by without this property. It is only used when starting a build job. We should be able to pass in the engine type when we call `IBuildJobService.StartBuildJobAsync`. Then one place where it is tricky is when we start the postprocess job from the `ClearMLMonitorService`. If we have some way to differentiate between the engine types from the ClearML task metadata, then it should be doable.
___
*[`src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs` line 72 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZf6VA1moZ0cIluaUX:-O-2pSyz93O-dErRss0n:b-8kx7u6) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs#L72)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I changed it back to .zip.  Dotnet handles .zip easier than tar.gz and python doesn't care.
</blockquote></details>

You can use the `GZipStream` and `TarFile` classes to extract the `.tar.gz` file. [Here](https://www.nikouusitalo.com/blog/how-to-natively-read-tgz-files-with-the-new-c-tarreader-class/) is an example that uses `TarReader`, but it should be easy to adapt to `TarFile`.


<!-- Sent from Reviewable.io -->

2024-06-11 12:32 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs` line 72 at r9](https://reviewable.io/reviews/sillsdev/machine/200#-NzZf6VA1moZ0cIluaUX:-O-6HJ_wBPrqUlDut8jo:bbh9nt6) ([raw file](https://github.com/sillsdev/machine/blob/4c89be13de36a74a497602b5b3e380c3761c4851/src/SIL.Machine.AspNetCore/Services/ThotSmtModelFactory.cs#L72)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can use the `GZipStream` and `TarFile` classes to extract the `.tar.gz` file. [Here](https://www.nikouusitalo.com/blog/how-to-natively-read-tgz-files-with-the-new-c-tarreader-class/) is an example that uses `TarReader`, but it should be easy to adapt to `TarFile`.
</blockquote></details>

done (by you).


<!-- Sent from Reviewable.io -->

2024-06-11 15:30 UTC, ddaspit reviewed
> Reviewed 5 of 8 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_rQPD8yBVOnoJx3u2:-O-6uzU0-DhhCQmLEbFX:bi8d0o1) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The only concern would be historic jobs that died during the job but because of the hangfire restart issue, are just languishing in an incomplete state.  When the hangfire issue is fixed, the jobs will start back up again and will fail because they don't have a translation engine type.  That is why I am considering just killing the jobs that never completed.
  In terms of differentiating, I don't know if we can reliably.  We could update the database manually by stripping the engine type from Serval and putting into the mongo DB, but that would be an update script, or a database conversion.  Do we want to go down that route?  Again, I recommend just deleting all jobs from Machine.
</blockquote></details>

We should meet to come up with a plan.


<!-- Sent from Reviewable.io -->

2024-06-11 17:18 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_rQPD8yBVOnoJx3u2:-O-77rPGEV58CXvVpII5:b-9i0f7) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should meet to come up with a plan.
</blockquote></details>

1. Write python script to delete "currentBuild" from every translation engine and remove the machine_jobs hangfire database.
2. Test on Internal QA:  using 1.4.5, (1) run a set of E2E tests.  (2) Spin down machine. (3) Run Python script (6) spin up 1.5.0 (7) rebuild an existing SMT and NMT engine. (8) run all E2E tests again.
3. For production, (1) make sure there are no running builds (2) spin down Serval (3) run script (4) Spin up Serval 1.5


<!-- Sent from Reviewable.io -->

2024-06-11 17:18 UTC, johnml1135 commented
*[`src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs` line 8 at r6](https://reviewable.io/reviews/sillsdev/machine/200#-Ny_rQPD8yBVOnoJx3u2:-O-7Ikrq5WVJ3ykwx66j:b-2cek4e) ([raw file](https://github.com/sillsdev/machine/blob/32168eed04a09a10533485e18818940b98060bab/src/SIL.Machine.AspNetCore/Models/TranslationEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

1. Write python script to delete "currentBuild" from every translation engine and remove the machine_jobs hangfire database.
2. Test on Internal QA:  using 1.4.5, (1) run a set of E2E tests.  (2) Spin down machine. (3) Run Python script (6) spin up 1.5.0 (7) rebuild an existing SMT and NMT engine. (8) run all E2E tests again.
3. For production, (1) make sure there are no running builds (2) spin down Serval (3) run script (4) Spin up Serval 1.5
</blockquote></details>

https://github.com/sillsdev/serval/issues/407


<!-- Sent from Reviewable.io -->

2024-06-11 19:24 UTC, ddaspit reviewed
You still need to revert the last commit, then I will approve.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200#-:-O-7kVn54uj5kRoi2-lz:b-llouq0)* status: 63 of 67 files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-06-11 19:37 UTC, johnml1135 commented
Reverted.





<!-- Sent from Reviewable.io -->

2024-06-11 20:15 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/200#-:-O-7w9VH8tG_1PZBa3wl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-06-11 23:02 UTC, merged