Word alignment try 2
sillsdev/machine pull request #267
Opened 2024-11-05 21:58 UTC by johnml1135

Add word alignment engine to IInteractiveTranslationEngine.

2024-11-05 22:36 UTC, ddaspit reviewed
What is this change for?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OAyTAgvDdPDz2DSoQf2:b-gnqp31)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-06 16:09 UTC, johnml1135 commented
This is needed for adding the word alignment engine to Serval.  Just exposing the alignment endpoints to the interactive engine.





<!-- Sent from Reviewable.io -->

2024-11-06 16:11 UTC, johnml1135 commented
This needs to be merged and released before the Serval changes will be able to compile.





<!-- Sent from Reviewable.io -->

2024-11-06 20:40 UTC, ddaspit reviewed
I'm still not sure I understand what this is for. There are already interfaces for word alignment models. Also, phrase alignment isn't word alignment. That is specific to the Thot SMT engine.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OB2Be093KgCO5gbDS2X:byrol75)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-08 21:23 UTC, johnml1135 commented
Hmm.  It wold be quite a bit of reworking.  I would have to use a different wording than `ThotWordAlignmentModel` because that is just referring to the asymmetrical alignment, not the symmetrical alignment with tokenizer.  In python, the word aligner has the tokenizer connected to it.  I could rework the Machine word aligner to have the tokenizer in it, but that would be a fair amount of work.  The solution I have appears to be a good minimal solution - treat the ThotSmtModel as a SymmetrizedWordAlignmentModel with tokenizers - it already has the capability of having the truecaser as null.  

Otherwise, I think I would have to create base class of ThotSmtModel called ThotSymmetrizedWordAlignmentModelWithTokenizer? in which 1/2 of the functionality of ThotSmtModel is implemented.  And even then, all the configurations and trainers and everything else would need to be torn apart and rewritten.

I think this minimal change is the best solution - it looks like a word aligner on Serval but is just an SMT model underneath. 





<!-- Sent from Reviewable.io -->

2024-11-09 02:57 UTC, ddaspit reviewed
The `ThotSmtModel` is a full phrased-based SMT system and takes a lot more computation and time to train. The phrase alignment from the SMT model uses a different algorithm than the word alignment models and is much more expensive. Unfortunately, it is not a replacement for the word alignment models. We should meet to discuss how best to proceed. I'm sure if I had a better understanding of what you are trying to achieve, we can come up with a good solution.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OBDpxOh3h7EPS7DLJgO:bu8mlkc)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-24 19:08 UTC, Enkidu93 commented
I'll need to update the branch and otherwise might have some small TODOs floating around, but I think this PR is generally ready for review, @johnml1135 @ddaspit :partying_face:

2025-01-27 17:03 UTC, johnml1135 commented
*[`src/SIL.Machine.Tool/ToolHelpers.cs` line 17 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHchrtn06Ah81otPkO6:-OHchrtn06Ah81otPkO7:bd2q084) ([raw file](https://github.com/sillsdev/machine/blob/831986858cba2c1ee19ba6dcae904a21a4d44c58/src/SIL.Machine.Tool/ToolHelpers.cs#L17)):*
> ```Smalltalk
> internal static class ToolHelpers
> {
>     public const string FastAlign = "fast_align";
> ```

Why were these helpers moved from the generic "ToolHelpers" to the specific ones for symmetrization and thot?


<!-- Sent from Reviewable.io -->

2025-01-27 17:16 UTC, johnml1135 commented
I am thinking (though not remembering fully) - are any tests needed?  It doesn't really seem to be changing anything core, just rearranging where the content is and exposing it in a way more friendly to Serval.

@ddaspit - do you know if anyone will be affected by the changes we are making to these libraries?





<!-- Sent from Reviewable.io -->

2025-01-27 20:13 UTC, ddaspit requested changes
> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: all files reviewed, 7 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Translation/WordAlignmentResult.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdNGCXDFvSvnIEag-W:-OHdNGCXDFvSvnIEag-X:b-avjg5u) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/WordAlignmentResult.cs#L7)):*
> ```Smalltalk
> namespace SIL.Machine.Translation
> {
>     public class WordAlignmentResult
> ```

What is this class used for?
___
*[`src/SIL.Machine/Translation/SymmetrizationHeuristic.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdN5WZ8IbUSxoV_egB:-OHdN5WZ8IbUSxoV_egC:bwindox) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/SymmetrizationHeuristic.cs#L46)):*
> ```Smalltalk
>     }
> 
>     public static class SymmetrizationHelpers
> ```

If this is only used in SIL.Machine.Tool, then you can just leave it there.
___
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs` line 16 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMHEfDMI1RygavRSH:-OHdMHEfDMI1RygavRSI:b-vuycxj) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs#L16)):*
> ```Smalltalk
>     }
> 
>     public static class ThotWordAlignmentHelpers
> ```

If this is only used in SIL.Machine.Tool, I would just leave it there.
___
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs` line 124 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdOApW15mRUv9KF_7E:-OHdOApW15mRUv9KF_7F:b48ptb3) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs#L124)):*
> ```Smalltalk
>         }
> 
>         public ITrainer CreateTrainer(IParallelTextCorpus corpus, ITokenizer<string, int, string> tokenizer = null)
> ```

We should handle this the same way that we handle it in `ThotSmtModel`. Add new properties for the source and target tokenizers to this class.
___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OHdL81Q8U7NZrAqhiL6:b-u6wy8h) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
> ```Smalltalk
> namespace SIL.Machine.Translation
> {
>     public interface IWordAlignmentEngine : IWordAligner, IDisposable
> ```

What is the purpose of this interface?
___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMOFB9XtS6e4CUFzd:-OHdMOFB9XtS6e4CUFze:b-ert6vn) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Corpora/AlignedWordPair.cs#L29)):*
> ```Smalltalk
>         {
>             alignedWordPairs = null;
>             try
> ```

You should only use exceptions for exceptional cases and not normal logic like this. Is this to catch the case where integers cannot be parsed? If so, you should just check the result from `int.TryParse`.


<!-- Sent from Reviewable.io -->

2025-01-27 21:59 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OHdksDd5Eg9HJbkldLc:b7wgard) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the purpose of this interface?
</blockquote></details>

It was more logical (when I was writing it) to make the `SymmetrizedWordAlignmentEngine` separate from the `SymmetrizedWordAlignmentModel`, but I am seeing that I am not using the engine, nor the engine interface anywhere in particular.  It mirrors the breakdown of engines and models in the translation space, but has not analogous use cases.  I can't determine right now when AQUA is added if it will use the engine itself or not.


<!-- Sent from Reviewable.io -->

2025-01-27 22:00 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/SymmetrizationHeuristic.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdN5WZ8IbUSxoV_egB:-OHdltl3Cf40Y7YUEpAP:b-dxcbts) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/SymmetrizationHeuristic.cs#L46)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If this is only used in SIL.Machine.Tool, then you can just leave it there.
</blockquote></details>

Makes sense.


<!-- Sent from Reviewable.io -->

2025-01-27 22:00 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMOFB9XtS6e4CUFzd:-OHdlvO31tODUllzjCeq:b-dxcbts) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Corpora/AlignedWordPair.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should only use exceptions for exceptional cases and not normal logic like this. Is this to catch the case where integers cannot be parsed? If so, you should just check the result from `int.TryParse`.
</blockquote></details>

Makes sense.


<!-- Sent from Reviewable.io -->

2025-01-27 22:04 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OHdmeHS8jGznYdS7o0B:b9z8yq4) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It was more logical (when I was writing it) to make the `SymmetrizedWordAlignmentEngine` separate from the `SymmetrizedWordAlignmentModel`, but I am seeing that I am not using the engine, nor the engine interface anywhere in particular.  It mirrors the breakdown of engines and models in the translation space, but has not analogous use cases.  I can't determine right now when AQUA is added if it will use the engine itself or not.
</blockquote></details>

Correct that - it's used in Serval.  A lot of these changes are to better expose WordAlignment to Serval for use.


<!-- Sent from Reviewable.io -->

2025-01-27 22:09 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/WordAlignmentResult.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdNGCXDFvSvnIEag-W:-OHdmU9N1mt5s_otjgve:btpz330) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/WordAlignmentResult.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is this class used for?
</blockquote></details>

It's used a handful of places in Serval - though it should likely be removed.  It was used more when the SMT engine and the statistical engine were sharing more infrastructure.  This should be removed and replaced in all locations with WordAlignmentResult from Serval.WordAlignment.Models.


<!-- Sent from Reviewable.io -->

2025-01-27 22:10 UTC, johnml1135 commented
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs` line 124 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdOApW15mRUv9KF_7E:-OHdo9rz0w8NkyXQdrDe:btahtzx) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs#L124)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should handle this the same way that we handle it in `ThotSmtModel`. Add new properties for the source and target tokenizers to this class.
</blockquote></details>

sounds good to me.


<!-- Sent from Reviewable.io -->

2025-01-27 22:10 UTC, johnml1135 commented
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs` line 16 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMHEfDMI1RygavRSH:-OHdoHYO3Dv4dUigARXg:bii264s) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If this is only used in SIL.Machine.Tool, I would just leave it there.
</blockquote></details>

Ok by me.


<!-- Sent from Reviewable.io -->

2025-01-27 22:11 UTC, johnml1135 commented
I took the first pass.





<!-- Sent from Reviewable.io -->

2025-01-30 19:57 UTC, ddaspit reviewed
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: 18 of 20 files reviewed, 7 unresolved discussions (waiting on @johnml1135)

___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OHsmKHkDHVu0q74Z7VS:b-s1qjm4) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Correct that - it's used in Serval.  A lot of these changes are to better expose WordAlignment to Serval for use.
</blockquote></details>

Can we use one of the existing interfaces (`IWordAlignmentModel` or `IWordAligner`)? 


<!-- Sent from Reviewable.io -->

2025-02-03 16:50 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIBhTS_ElIKZbxciyyH:b-1daupr) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can we use one of the existing interfaces (`IWordAlignmentModel` or `IWordAligner`)?
</blockquote></details>

At the Serval level, we needed a distinction between the Engine and the Model, especially to support the Statistical engine service and the WordAlignmentEngineState.  Both don't use the Trainer routines and make more sense to just load the engine.


<!-- Sent from Reviewable.io -->

2025-02-03 16:53 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: 14 of 20 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMOFB9XtS6e4CUFzd:-OIBa08f7IQ3PxbslPVr:byh4u10) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Corpora/AlignedWordPair.cs#L29)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Makes sense.
</blockquote></details>

Is this better? It's a little odd, but it'd be nice to have a `TryParse` function for use in the serializer.
___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIBaLup-ywuuFV2a_qX:bhu9dz3) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can we use one of the existing interfaces (`IWordAlignmentModel` or `IWordAligner`)?
</blockquote></details>

@johnml1135, would you like to give your rationale as to why we couldn't use one of the existing interfaces like Damien mentioned since you're the one who architected the change?
___
*[`src/SIL.Machine.Tool/ToolHelpers.cs` line 17 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHchrtn06Ah81otPkO6:-OIB_XZa-D6HgRIsu_rw:b-llxfhl) ([raw file](https://github.com/sillsdev/machine/blob/831986858cba2c1ee19ba6dcae904a21a4d44c58/src/SIL.Machine.Tool/ToolHelpers.cs#L17)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why were these helpers moved from the generic "ToolHelpers" to the specific ones for symmetrization and thot?
</blockquote></details>

I don't know. I think you did that, right? Sounds like you're OK moving them back.
___
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs` line 124 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdOApW15mRUv9KF_7E:-OIBiX9CCpY0ts6Ejq3v:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModel.cs#L124)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

sounds good to me.
</blockquote></details>

Done.
___
*[`src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs` line 16 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMHEfDMI1RygavRSH:-OIBh3Kt8GYhc6zuux2_:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine.Translation.Thot/ThotWordAlignmentModelType.cs#L16)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ok by me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-03 16:55 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Translation/SymmetrizationHeuristic.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdN5WZ8IbUSxoV_egB:-OIBjDn9ApkZfzo5whc3:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/SymmetrizationHeuristic.cs#L46)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Makes sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-03 17:00 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIBkPVcAXUaftIQqd2J:bg69c1) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

@johnml1135, would you like to give your rationale as to why we couldn't use one of the existing interfaces like Damien mentioned since you're the one who architected the change?
</blockquote></details>

Sorry, I had this drafted before I saw your message 


<!-- Sent from Reviewable.io -->

2025-02-03 17:26 UTC, Enkidu93 commented
*[`src/SIL.Machine/Translation/WordAlignmentResult.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdNGCXDFvSvnIEag-W:-OIBpzRy0GT4Hp_UrbEn:b-fm30h1) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/WordAlignmentResult.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It's used a handful of places in Serval - though it should likely be removed.  It was used more when the SMT engine and the statistical engine were sharing more infrastructure.  This should be removed and replaced in all locations with WordAlignmentResult from Serval.WordAlignment.Models.
</blockquote></details>

OK, It will create a dependency that `Serval.Machine.Shared` has on `Serval.WordAlignment`. As long as that's alright with everyone, I can do it.


<!-- Sent from Reviewable.io -->

2025-02-03 17:34 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: 6 of 20 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Translation/WordAlignmentResult.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdNGCXDFvSvnIEag-W:-OIBs1WY2WW0hGne-8WV:b-imib65) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/WordAlignmentResult.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, It will create a dependency that `Serval.Machine.Shared` has on `Serval.WordAlignment`. As long as that's alright with everyone, I can do it.
</blockquote></details>

I guess that's how it already is for `Serval.Translation`, so that shouldn't be an issue. I'll just not use a global import.


<!-- Sent from Reviewable.io -->

2025-02-03 18:05 UTC, johnml1135 commented
*[`src/SIL.Machine.Tool/ToolHelpers.cs` line 17 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHchrtn06Ah81otPkO6:-OIBzHNU60GtAHa8cspd:b-u6qadj) ([raw file](https://github.com/sillsdev/machine/blob/831986858cba2c1ee19ba6dcae904a21a4d44c58/src/SIL.Machine.Tool/ToolHelpers.cs#L17)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I don't know. I think you did that, right? Sounds like you're OK moving them back.
</blockquote></details>

Sure - move them back.


<!-- Sent from Reviewable.io -->

2025-02-03 19:37 UTC, Enkidu93 reviewed
@ddaspit, @johnml1135, I believe I've responded to all comments and that this PR is ready for review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OICJG7s0aWaGOM5Re-c:bzcvuxe)* status: 5 of 20 files reviewed, 6 unresolved discussions (waiting on @ddaspit)

___
*[`src/SIL.Machine.Tool/ToolHelpers.cs` line 17 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHchrtn06Ah81otPkO6:-OICJ35U4NTGRfjLD3Bk:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/831986858cba2c1ee19ba6dcae904a21a4d44c58/src/SIL.Machine.Tool/ToolHelpers.cs#L17)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Sure - move them back.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-03 20:07 UTC, johnml1135 reviewed
> Reviewed 20 of 20 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 9 of 9 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: all files reviewed, 6 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2025-02-04 19:32 UTC, ddaspit reviewed
> Reviewed 17 of 17 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMOFB9XtS6e4CUFzd:-OIHPao24QUWPflSiVWJ:blrwtbv) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Corpora/AlignedWordPair.cs#L29)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this better? It's a little odd, but it'd be nice to have a `TryParse` function for use in the serializer.
</blockquote></details>

Looks good. I would return as soon as a `TryParseIndex` fails.
___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIHMQYn5X2VmmkSoYaQ:bhufylo) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry, I had this drafted before I saw your message
</blockquote></details>

I took a look at the Serval code to better understand how the interface is being used. It looks like `StatisticalEngineService` needs to call `GetBestAlignedWordPairs`. Rather than add a new interface, we should add `GetBestAlignedWordPairs` to the `IWordAligner` interface. It makes sense there anyway. Then, we can use `IWordAligner` instead. It should be easy to implement for most classes that implement the `IWordAligner` interface. You can just add a default implementation in `WordAlignerBase` that looks something like this:

```cs
WordAlignmentMatrix matrix = Align(sourceSegment, targetSegment);
return matrix.ToAlignedWordPairs();
```
___
*[`src/SIL.Machine/Translation/IWordAlignmentModel.cs` line 10 at r8](https://reviewable.io/reviews/sillsdev/machine/267#-OIHR0Je1mIVQOLYqQvM:-OIHR0Je1mIVQOLYqQvN:bqzrg3f) ([raw file](https://github.com/sillsdev/machine/blob/d46b4672b3e8e0128aacf90f89c0327313c0e184/src/SIL.Machine/Translation/IWordAlignmentModel.cs#L10)):*
> ```Smalltalk
>     {
>         ITrainer CreateTrainer(IParallelTextCorpus corpus);
>         Task SaveAsync(CancellationToken cancellationToken = default);
> ```

We shouldn't need the `Save` methods. The `IWordAlignmentModel` interface provides no methods that update the model.
___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 100 at r8](https://reviewable.io/reviews/sillsdev/machine/267#-OIHPjLN9Act_D4fjZcv:-OIHPjLN9Act_D4fjZcw:b-ljf0tq) ([raw file](https://github.com/sillsdev/machine/blob/d46b4672b3e8e0128aacf90f89c0327313c0e184/src/SIL.Machine/Corpora/AlignedWordPair.cs#L100)):*
> ```Smalltalk
>                 return true;
>             }
>             if (indexString == "NULL")
> ```

I would perform this check first.


<!-- Sent from Reviewable.io -->

2025-02-04 20:41 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/IWordAlignmentModel.cs` line 10 at r8](https://reviewable.io/reviews/sillsdev/machine/267#-OIHR0Je1mIVQOLYqQvM:-OIHgapx6h39-_mYhf20:b-h4suva) ([raw file](https://github.com/sillsdev/machine/blob/d46b4672b3e8e0128aacf90f89c0327313c0e184/src/SIL.Machine/Translation/IWordAlignmentModel.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We shouldn't need the `Save` methods. The `IWordAlignmentModel` interface provides no methods that update the model.
</blockquote></details>

I agree - see other comments.


<!-- Sent from Reviewable.io -->

2025-02-05 13:13 UTC, johnml1135 commented
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OILDYF_2agoJX6YQS-2:b-udegeq) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I took a look at the Serval code to better understand how the interface is being used. It looks like `StatisticalEngineService` needs to call `GetBestAlignedWordPairs`. Rather than add a new interface, we should add `GetBestAlignedWordPairs` to the `IWordAligner` interface. It makes sense there anyway. Then, we can use `IWordAligner` instead. It should be easy to implement for most classes that implement the `IWordAligner` interface. You can just add a default implementation in `WordAlignerBase` that looks something like this:

```cs
WordAlignmentMatrix matrix = Align(sourceSegment, targetSegment);
return matrix.ToAlignedWordPairs();
```
</blockquote></details>

The IWordAligner interface does not handle Tokenization.  So either we add tokenization to the IWordAligner interface, or we have a different interface.  The lack of tokenization is why I didn't use it before.


<!-- Sent from Reviewable.io -->

2025-02-06 15:32 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIQrxEA-UqWv00lsFOE:b6wqbiq) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The IWordAligner interface does not handle Tokenization.  So either we add tokenization to the IWordAligner interface, or we have a different interface.  The lack of tokenization is why I didn't use it before.
</blockquote></details>

A while back I did a refactor of the translation interfaces to support passing strings as well as lists of tokens. Do you want something similar for the word alignment interfaces? I never got around to doing the same thing for the word alignment interfaces. I always planned to, so if we need it, then we should add it. It does look like the `IWordAlignmentEngine` interface does not have any methods like that though.


<!-- Sent from Reviewable.io -->

2025-02-10 19:29 UTC, johnml1135 commented
Is everything ready?  There are still a few comments unaddressed.  I am ok with the removing of the engines and just squashing the behavior into the higher level (the model level). 





<!-- Sent from Reviewable.io -->

2025-02-10 19:53 UTC, Enkidu93 reviewed
Sorry - I missed a round of Damien's comments somehow. I think everything's done now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OIlPrN40Ll4bxM69URg:b-h8q56f)* status: 4 of 20 files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 29 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdMOFB9XtS6e4CUFzd:-OIlP9du4Xx-vRRiRz3O:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Corpora/AlignedWordPair.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Looks good. I would return as soon as a `TryParseIndex` fails.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/AlignedWordPair.cs` line 100 at r8](https://reviewable.io/reviews/sillsdev/machine/267#-OIHPjLN9Act_D4fjZcv:-OIlPNPb03bOS06fBZFV:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/d46b4672b3e8e0128aacf90f89c0327313c0e184/src/SIL.Machine/Corpora/AlignedWordPair.cs#L100)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would perform this check first.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Translation/IWordAlignmentEngine.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/267#-OHdL81Q8U7NZrAqhiL5:-OIlPgCLDZrKUVeHKQvJ:balgtby) ([raw file](https://github.com/sillsdev/machine/blob/eb763b037366256d77c1b31e79e785eaf97c36f6/src/SIL.Machine/Translation/IWordAlignmentEngine.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

A while back I did a refactor of the translation interfaces to support passing strings as well as lists of tokens. Do you want something similar for the word alignment interfaces? I never got around to doing the same thing for the word alignment interfaces. I always planned to, so if we need it, then we should add it. It does look like the `IWordAlignmentEngine` interface does not have any methods like that though.
</blockquote></details>

(I'm sorry - I think I missed your earlier comment, Damien. I think this fine now, right?)
___
*[`src/SIL.Machine/Translation/IWordAlignmentModel.cs` line 10 at r8](https://reviewable.io/reviews/sillsdev/machine/267#-OIHR0Je1mIVQOLYqQvM:-OIlPoSW31O4_niAIy2E:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/d46b4672b3e8e0128aacf90f89c0327313c0e184/src/SIL.Machine/Translation/IWordAlignmentModel.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I agree - see other comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-11 19:33 UTC, johnml1135 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2025-02-11 23:21 UTC, Enkidu93 commented
> > Reviewed 13 of 13 files at r10, 4 of 4 files at r11, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)_ status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)
> 
> _[`src/SIL.Machine/Translation/SymmetrizedWordAlignmentModel.cs` line 31 at r11](https://reviewable.io/reviews/sillsdev/machine/267#-OIqeQnIBDmZ9Ae8649H:-OIqeQnIBDmZ9Ae8649I:bki89x6) ([raw file](https://github.com/sillsdev/machine/blob/04d23a5fec1991a64cccff16208dc57fdea4d189/src/SIL.Machine/Translation/SymmetrizedWordAlignmentModel.cs#L31)):_
> 
> > ```smalltalk
> >         }
> > 
> >         public IWordAlignmentModel DirectWordAlignmentEngine
> > ```
> 
> This property was renamed. It should be reverted back to the original name.
> 
> _[`src/SIL.Machine/Translation/SymmetrizedWordAlignmentModel.cs` line 41 at r11](https://reviewable.io/reviews/sillsdev/machine/267#-OIqeZM73skOxbBMOKxs:-OIqeZM73skOxbBMOKxt:bki89x6) ([raw file](https://github.com/sillsdev/machine/blob/04d23a5fec1991a64cccff16208dc57fdea4d189/src/SIL.Machine/Translation/SymmetrizedWordAlignmentModel.cs#L41)):_
> 
> > ```smalltalk
> >         }
> > 
> >         public IWordAlignmentModel InverseWordAlignmentEngine
> > ```
> 
> This property was renamed. It should be reverted back to the original name.

Done. Sorry I missed that!

2025-02-12 13:14 UTC, johnml1135 reviewed
> Reviewed 17 of 17 files at r8, 4 of 4 files at r9, 13 of 13 files at r10, 4 of 4 files at r11, 13 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2025-02-12 20:45 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 13 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267#-:-OIvuFVw2iEL1XDr2rRL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-12 22:10 UTC, johnml1135 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/267)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-12 22:45 UTC, merged