NParallelTextCorpus
sillsdev/machine pull request #270
Opened 2024-11-08 21:56 UTC by Enkidu93

Here's the Machine PR needed to support the updates to Serval. I'll put in a PR there as well, but of course it will require an updated version of Machine once this goes through; but I'll put it in now anyways so that you'll be able to see how it'll be used.

2024-11-08 21:59 UTC, Enkidu93 commented
Fixes https://github.com/sillsdev/machine/issues/266

2024-11-08 22:01 UTC, Enkidu93 commented
The only outstanding bullet point from the original description that I think I haven't covered is: "NParallelTextCorpora will take a parameter to determine how equivalent references are combined: choose first, combine all, or permutate all". Is this something we'll really want? Or is there a behavior we'll always prefer? Right now it's permutating.

2024-11-11 15:53 UTC, johnml1135 commented
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQv_WPEwPJp8rQZkLG:-OBQv_WPEwPJp8rQZkLH:b-mlofbf):*
Can you clean up this history?


<!-- Sent from Reviewable.io -->

2024-11-11 16:12 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 577 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQzuK013z_H4kTamMs:-OBQzuK013z_H4kTamMt:b-kch5g2) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L577)):*
> ```Smalltalk
>             public override IEnumerable<TextRow> GetRows(IEnumerable<string> textIds)
>             {
>                 int indexOfInRangeRow = -1;
> ```

Can you explain in English what the indexOfInRangeRow is trying to accomplish?


<!-- Sent from Reviewable.io -->

2024-11-11 16:15 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 586 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR-Z5n-AMAtcqseHPm:-OBR-Z5n-AMAtcqseHPn:bo3h29j) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L586)):*
> ```Smalltalk
>                         .ToList();
>                     IReadOnlyList<int> indices =
>                         nonEmptyIndices.Count > 0 ? nonEmptyIndices : Enumerable.Range(0, nRow.N).ToList();
> ```

How does this logic work with AllRows?  Are they blank rows being send down?


<!-- Sent from Reviewable.io -->

2024-11-11 16:37 UTC, Enkidu93 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 586 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR-Z5n-AMAtcqseHPm:-OBR4I2i-l5wa5Dj39me:b5j1jun) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L586)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How does this logic work with AllRows?  Are they blank rows being send down?
</blockquote></details>

Could you elaborate on the connection with allRows? Yes, there may be empty rows output if all the rows available are empty. But it would be an unusual circunstance.


<!-- Sent from Reviewable.io -->

2024-11-11 16:37 UTC, Enkidu93 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 577 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQzuK013z_H4kTamMs:-OBR4-Nr36chSNd0McL6:b-qou0cu) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L577)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you explain in English what the indexOfInRangeRow is trying to accomplish?
</blockquote></details>

The point of the variable is to keep track of whether you previously picked a row from a particular source that was the beginning of a range. This way, you'll keep picking from that source until the range is finished.


<!-- Sent from Reviewable.io -->

2024-11-11 16:37 UTC, Enkidu93 commented
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQv_WPEwPJp8rQZkLG:-OBR3nOA1m2aTNKXVFPP:b-v2cpat):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you clean up this history?
</blockquote></details>

Sure! Would it be simpler just to squash this when I'm merging/rebasing?


<!-- Sent from Reviewable.io -->

2024-11-11 16:41 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 222 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR5R_A97J6dsp-2IcH:-OBR5R_A97J6dsp-2IcI:b-t6n0nv) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L222)):*
> ```Smalltalk
>                     {
>                         int compareAlignmentCorpus = -1;
>                         if (AlignmentCorpus != null)
> ```

What exactly is the function of the alignment corpus?  Why is it active here, but not above when not all corpora were in lock-step?


<!-- Sent from Reviewable.io -->

2024-11-11 16:46 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 250 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR6G1ZCcmNN3iLE8u8:-OBR6G1_0dpXjMc8eNCG:bk60hwd) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L250)):*
> ```Smalltalk
>                                     && minRefIndexes.All(j => j == i || !AllRowsList[j])
>                                 )
>                                 .Any(b => b)
> ```

Many of these are cryptic logic.  Let's have at least a sentence per set of logic.  "doing it the right way" would likely involve creating a dozen or so sub-functions to do the intermediate processing, but that may lead to more confusion.  I just want to have enough bread crumbs that when someone comes back in 3 years, they'll be able to understand what is going on here without having to spend 3 days.


<!-- Sent from Reviewable.io -->

2024-11-11 16:50 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 250 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR6G1ZCcmNN3iLE8u8:-OBR79WXCyEu-XzWv4F7:b21po1p) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L250)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Many of these are cryptic logic.  Let's have at least a sentence per set of logic.  "doing it the right way" would likely involve creating a dozen or so sub-functions to do the intermediate processing, but that may lead to more confusion.  I just want to have enough bread crumbs that when someone comes back in 3 years, they'll be able to understand what is going on here without having to spend 3 days.
</blockquote></details>

Or, if you take the complicated logic in these if statements and make functions with descriptive names, like below with "rangeInfo.IsInRange && AllInRangeHaveSegments(currentIncompleteRows)".  That is decodable - the above logic less so.


<!-- Sent from Reviewable.io -->

2024-11-11 16:59 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 345 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR9cIM1pWQHLMgOM1Q:-OBR9cIM1pWQHLMgOM1R:b-9z6a20) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L345)):*
> ```Smalltalk
> 
>             object[] defaultRefs = new object[] { };
>             if (rows.Any(r => r != null))
> ```

Why rows.Any if you already threw a Argument null exception above?


<!-- Sent from Reviewable.io -->

2024-11-11 17:17 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 76 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRAQdV6SM-fCoBBruk:-OBRAQdV6SM-fCoBBrul:b-l8rpda) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L76)):*
> ```Smalltalk
>                     var enumerator = Corpora[i].GetRows(filterTextIds).GetEnumerator();
>                     enumeratedCorpora.Add(
>                         new TextCorpusEnumerator(enumerator, Corpora[0].Versification, Corpora[i].Versification)
> ```

My understanding was that this line (and this line alone) fixed all versification issues.  Why is this here and the "correctVersification" later?


<!-- Sent from Reviewable.io -->

2024-11-11 17:20 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 373 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBREHVm4XwhdI4bAQfy:-OBREHVm4XwhdI4bAQfz:b-4lw5zq) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L373)):*
> ```Smalltalk
>                 NSegments = rows.Select(r => r?.Segment ?? Array.Empty<string>()).ToArray(),
>                 NFlags = flags.ToReadOnlyList(),
>                 AlignedWordPairs = alignedWordPairs
> ```

I would have assumed that AlignedWordPairs was pushed up to ParallelTextCorpus, as it really only makes sense with two corpora.  


<!-- Sent from Reviewable.io -->

2024-11-11 18:37 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextRow.cs` line 49 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRVmdREhw57wW-k4rx:-OBRVmdREhw57wW-k4ry:bu0hp0e) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextRow.cs#L49)):*
> ```Smalltalk
>         public string GetText(int i) => string.Join(" ", NSegments[i]);
> 
>         public IReadOnlyCollection<AlignedWordPair> AlignedWordPairs { get; set; }
> ```

Again, I am skeptical whether there should be AlignedWordPairs in the NParallelTextCorpus/Row at all.  I think it makes much more sense with "Pairs" of corpora.


<!-- Sent from Reviewable.io -->

2024-11-11 18:59 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/CorporaExtensionsTests.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRa2n1DJ3EElbfMY7a:-OBRa2n1DJ3EElbfMY7b:bjg35ea) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/CorporaExtensionsTests.cs#L149)):*
> ```Smalltalk
>         {
>             Assert.That(rows[0].Text, Is.EqualTo("source 1 segment 1 ."));
>             Assert.That(rows[1].Text, Is.EqualTo("source 1 segment 2 ."));
> ```

Can you use a different seed to make it not just be all from source 1?  It needs to fail if it were "first".


<!-- Sent from Reviewable.io -->

2024-11-11 19:00 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/CorporaExtensionsTests.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRa2n1DJ3EElbfMY7a:-OBRaE3UBuQv_n06OKl-:b-mpt0lb) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/CorporaExtensionsTests.cs#L149)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you use a different seed to make it not just be all from source 1?  It needs to fail if it were "first".
</blockquote></details>

Ah, 2 different seeds.


<!-- Sent from Reviewable.io -->

2024-11-11 19:07 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRbRCDAH66Q0A5UTD6:-OBRbRCDAH66Q0A5UTD7:b-njftu3) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L86)):*
> ```Smalltalk
>         var nParallelCorpus = new NParallelTextCorpus([corpus1, corpus2, corpus3]);
>         NParallelTextRow[] rows = nParallelCorpus.ToArray();
>         Assert.That(rows.Length, Is.EqualTo(1));
> ```

I'm confused... If I am correct the "AllRows" flag means that even if there is a row in the ITextCorpus that has a blank string for text, that reference is still included.  Here, there appear to be two issues:
* If not all corpora have text, text is not returned (shouldn't it be returned if any have text?
* The next test doesn't have blank strings with references in it to test the logic of AllRows.


<!-- Sent from Reviewable.io -->

2024-11-11 19:10 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRcCF26Einzg5uUfov:-OBRcCF26Einzg5uUfow:bi6hq0m) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L204)):*
> ```Smalltalk
>         NParallelTextRow[] rows = nParallelCorpus.ToArray();
>         Assert.That(rows.Length, Is.EqualTo(3));
>         Assert.That(rows[1].NRefs.All(r => r.Count == 0 || (int)r[0] == 2));
> ```

My understanding is that when you say "get rows"it always returns an array of size [N], including the blank strings.  Is that is what is happening here?


<!-- Sent from Reviewable.io -->

2024-11-11 19:14 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 415 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRdUlm3oMSFgLnqGrp:-OBRdUlm3oMSFgLnqGrq:b-4wcfkn) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L415)):*
> ```Smalltalk
>         NParallelTextRow[] rows = nParallelCorpus.ToArray();
>         Assert.That(rows.Length, Is.EqualTo(3), JsonSerializer.Serialize(rows));
>         Assert.That(rows[0].NRefs[0], Is.EquivalentTo(new object[] { 1 }));
> ```

I'm trying to figure out - so, wouldn't the ranges mandate that all three references be merged into one segment?


<!-- Sent from Reviewable.io -->

2024-11-11 19:16 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 562 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRdlNO32-EJ966zWzx:-OBRdlNO32-EJ966zWzy:b8oezl3) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L562)):*
> ```Smalltalk
>                     TextRow("text1", 1, "source segment 1 ."),
>                     TextRow("text1", 2, "source segment 2-1 ."),
>                     TextRow("text1", 2, "source segment 2-2 ."),
> ```

There should be an option for the "Many-to-many" or "condense it all down to 1", depending on if it is keyterms or scripture. 


<!-- Sent from Reviewable.io -->

2024-11-11 19:16 UTC, johnml1135 requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 15 unresolved discussions (waiting on @ddaspit and @Enkidu93)

___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 282 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR8DdQ22fuhcNWzed8:-OBR8DdQ22fuhcNWzed9:b-y80nz0) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L282)):*
> ```Smalltalk
>                                             foreach (NParallelTextRow r in CreateRows(rangeInfo, textRows))
>                                             {
>                                                 yield return r;
> ```

No quite understanding why you are doing N^2 logic and yielding matching pairs.
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR-j059Ep92JnimJrJ:-OBR-j059Ep92JnimJrK:bft48ze) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L9)):*
> ```Smalltalk
>         int Count(bool includeEmpty = true, IEnumerable<string> textIds = null);
> 
>         IEnumerable<NParallelTextRow> GetRows(IEnumerable<string> textIds);
> ```

AllRowsList is not needed here?


<!-- Sent from Reviewable.io -->

2024-11-11 19:17 UTC, johnml1135 commented
@Damien - I thought that for scripture verses, if there are multiple verses with the same reference, we merge them together and treat it as a single entity.  Is that is what is being done here?





<!-- Sent from Reviewable.io -->

2024-11-11 19:17 UTC, johnml1135 commented
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQv_WPEwPJp8rQZkLG:-OBReFIjBPl_KlKyiMko:b-re8e2n):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sure! Would it be simpler just to squash this when I'm merging/rebasing?
</blockquote></details>

Yes, that is fine.


<!-- Sent from Reviewable.io -->

2024-11-11 19:56 UTC, ddaspit requested changes
@Enkidu93 We only need the "permute all" behavior for now. We can always add support for other options in the future if we need them.

@johnml1135 The parallel text corpus only permutes. The scripture text corpus classes ensure that there aren't duplicate verses.

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBRGJ9bCQbPOs2Jd52C:b-sn1cbq)* status: all files reviewed, 41 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`-- commits` line 65 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBQv_WPEwPJp8rQZkLG:-OBRLrzn-S9FFE5e2g2H:brpkizg):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sure! Would it be simpler just to squash this when I'm merging/rebasing?
</blockquote></details>

Yes, you can clean this up when you squash the commits.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 373 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBREHVm4XwhdI4bAQfy:-OBRUAPQ3rRhcfvw9aIN:bevi3h2) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L373)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would have assumed that AlignedWordPairs was pushed up to ParallelTextCorpus, as it really only makes sense with two corpora.
</blockquote></details>

I agree. It doesn't really make sense in this context. Would it be difficult to move all of the alignment corpus handling to `ParallelTextCorpus`?
___
*[a discussion](https://reviewable.io/reviews/sillsdev/machine/270#-OBRd7TSD0HTx3laCKGB:-OBRd7TSD0HTx3laCKGC:b-gsz4xs) (no related file):*
@Enkidu93  Performance is very important in `NParallelTextCorpus`. I tried to point out small optimizations where I could, but I think it might be useful for you to go over the code with the following principles in mind:

1. Avoid iterating over a collection/enumerable multiple times. If you can do the same thing in a single loop that is better.
2. Similarly, avoid unnecessarilly creating collection instances.
3. Be careful with LINQ functions. Some functions might iterate over a collection unnecessarilly. Using the appropriate type of collection can help avoid these issues sometimes.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRTl0s273G6fEB_W-z:-OBRTl0s273G6fEB_W0-:b3c1w2z) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L24)):*
> ```Smalltalk
>         }
> 
>         public bool GetIsTokenized(int i) =>
> ```

I would rename this to `IsTokenized`.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRTdrd3Zi3vogW5C7k:-OBRTdrd3Zi3vogW5C7l:b-txpvsb) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L29)):*
> ```Smalltalk
>         public int N => Corpora.Count;
> 
>         public IReadOnlyList<bool> AllRowsList { get; set; }
> ```

I would just call this `AllRows`.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRVYTR3uZO0-EU5tyo:-OBRVYTR3uZO0-EU5typ:bql8an2) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L34)):*
> ```Smalltalk
>         public IComparer<object> RowRefComparer { get; }
> 
>         private static HashSet<string> GetTextIdsFromCorpora(
> ```

I feel like we can do everything in this method in one loop.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRVsiHE8AuTy7MFhH-:-OBRVsiHE8AuTy7MFhH0:b-pe5ek3) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L74)):*
> ```Smalltalk
>                 for (int i = 0; i < Corpora.Count; i++)
>                 {
>                     var enumerator = Corpora[i].GetRows(filterTextIds).GetEnumerator();
> ```

Only use `var` when the type is explict elsewhere in the line.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRWSfI7ka8NsKBmrqt:-OBRWSfI7ka8NsKBmrqu:b4nv0m4) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L82)):*
> ```Smalltalk
>                 if (AlignmentCorpus != null)
>                     alignmentEnumerator = AlignmentCorpus.GetRows(filterTextIds).GetEnumerator();
>                 rows = GetRows(enumeratedCorpora, alignmentEnumerator).ToList();
> ```

We want to avoid returning a list from a corpus. This causes the entire corpus to be loaded into memory, which we want to avoid, since it is possible for a corpus to be very large.  We should use `yield return`.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 95 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRXbzeEiJUk8Wuaaf9:-OBRXbzeEiJUk8WuaafA:b-7c7ocr) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L95)):*
> ```Smalltalk
>         }
> 
>         private bool AllInRangeHaveSegments(IList<TextRow> rows)
> ```

This method can be static.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 137 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRZoDGDbmYZe6z63Ct:-OBRZoDGDbmYZe6z63Cu:b-2zcvoq) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L137)):*
> ```Smalltalk
>                 {
>                     IList<int> minRefIndexes;
>                     IList<TextRow> currentRows = listOfEnumerators.Select(e => e.Current).ToArray();
> ```

When passing collections between functions, it can be useful to reference the collections by interface, so that the function parameters are more general, but when used inside of a function, there is no need.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 141 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRYawq6YW2syssg5sC:-OBRYawq6YW2syssg5sD:b6xnkwv) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L141)):*
> ```Smalltalk
>                     {
>                         minRefIndexes = MinRefIndexes(
>                             currentRows
> ```

You should check `completed`. We found that it is possible for `Current` to return a non-null value even when an enumerator is completed.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 155 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR_IHl6FZ8BqdNGkgW:-OBR_IHm-YZa9lUA0Yiu:b-pe5ek3) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L155)):*
> ```Smalltalk
>                         throw new CorpusAlignmentException(currentRows.Select(e => e.Ref.ToString()).ToArray());
>                     }
>                     var currentIncompleteRows = currentRows.Where((r, i) => !completed[i]).ToArray();
> ```

Only use `var` when the type is explict elsewhere in the line.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 160 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR_k0kBqetRFDvh8EN:-OBR_k0kBqetRFDvh8EO:boj9ce4) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L160)):*
> ```Smalltalk
>                     if (
>                         minRefIn [...]

2024-11-13 19:18 UTC, Enkidu93 reviewed
OK, great. I'm working through all the comments and have pushed fixes for some. Feel free to review or just wait until I've addressed everything to the best of my ability.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBaR7dbClNj6nBniEJU:b-e2zhke)* status: 1 of 10 files reviewed, 41 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[a discussion](https://reviewable.io/reviews/sillsdev/machine/270#-OBRd7TSD0HTx3laCKGB:-OBaR94d01v5Q-hGdmfM:b5k7sy4) (no related file):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

@Enkidu93  Performance is very important in `NParallelTextCorpus`. I tried to point out small optimizations where I could, but I think it might be useful for you to go over the code with the following principles in mind:

1. Avoid iterating over a collection/enumerable multiple times. If you can do the same thing in a single loop that is better.
2. Similarly, avoid unnecessarilly creating collection instances.
3. Be careful with LINQ functions. Some functions might iterate over a collection unnecessarilly. Using the appropriate type of collection can help avoid these issues sometimes.
</blockquote></details>

Thank you. I'm looking through and have already found a few things.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 248 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRNmTuExpMTBtKR1wf:-OBaRezoAHmyftylMVUP:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L248)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The parameters should be `IEnumerable` instead of arrays. Also, tt should return the interface.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 380 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBROBw7DTiPRZLFBDzd:-OBaRhZd4ENJz4RnwWww:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L380)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `corpus` parameter type should be the interface. Also, these operations should be in a separate `INParallelTextCorpus` region.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 546 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRON6wBqdyBfyp0ip2:-OBaRkup6WHoTHwq8Zcn:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L546)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is no need to specify the actual int values.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 558 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRPLue-oZn6f9jY2nw:-OBaRm2s8rfziE60I9Nd:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L558)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we need this field.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 571 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRQBt61uSiVsc9Xkp1:-OBaRpGXBCs_oGA9ideh:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L571)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can merge the `Select` and `All` functions into a single `All` call.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 573 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRQVsuDEAiO-5GlCDd:-OBaRqTyCyOpEwT2SiTw:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/CorporaExtensions.cs#L573)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should avoid using `First` or `Last` on lists/arrays.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR-j059Ep92JnimJrJ:-OBaRvXu7ksnB4jNUj3u:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

AllRowsList is not needed here?
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRTl0s273G6fEB_W-z:-OBaRwqP8ty08l6VBPV8:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L24)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `IsTokenized`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRTdrd3Zi3vogW5C7k:-OBaRx7d0GnnGeVr7iHd:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would just call this `AllRows`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRVYTR3uZO0-EU5tyo:-OBaRxv46aCVe8sovFi5:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I feel like we can do everything in this method in one loop.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 74 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRVsiHE8AuTy7MFhH-:-OBaRybG-kj1nODUvqUW:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L74)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Only use `var` when the type is explict elsewhere in the line.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 82 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRWSfI7ka8NsKBmrqt:-OBaRzbr46I7FZYcMBgi:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We want to avoid returning a list from a corpus. This causes the entire corpus to be loaded into memory, which we want to avoid, since it is possible for a corpus to be very large.  We should use `yield return`.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 95 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRXbzeEiJUk8Wuaaf9:-OBaS-VF3WIc8U73I0GY:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L95)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This method can be static.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParalle [...]

2024-11-13 22:43 UTC, ddaspit reviewed
In a subsequent PR, we should add all of the corpus operators that `ParallelTextCorpus` supports.

> Reviewed 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBbgQvl34L6A5R-Gd7H:br74rf5)* status: 9 of 10 files reviewed, 20 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRjBRjEXGtv3c4h_Pa:-OBbfzPLCXe53awf4b00:b-lpcyva) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L33)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This should just be a readonly field.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBbdimV5IkmqFIu0pn3:b-vudpjp) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
> ```Smalltalk
>         }
> 
>         public static ITextCorpus ChooseRandom(this INParallelTextCorpus corpus, int seed)
> ```

This should take a list of text corpora like `AlignMany`.
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXS8hEAXBcbYIUFQo:-OBbXS8hEAXBcbYIUFQp:b-rmsvah) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L8)):*
> ```Smalltalk
>     {
>         int N { get; }
>         IReadOnlyList<ITextCorpus> Corpora { get; }
> ```

The purpose of this interface is to use the decorator pattern to add support for corpus operations. This restricts what properties we can add to the interface. The `Corpora` property would be difficult to support in these operator decorators, so we should probably remove it.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 113 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXLiN8JEdQAWBHuMm:-OBbXLiN8JEdQAWBHuMn:b-fqp7d1) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L113)):*
> ```Smalltalk
>         )
>         {
>             {
> ```

It looks like there is an extra brace here.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 122 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbTysL0ByWMZXtAlpz:-OBbTysM5F6sjUFisC9A:bjvr5i2) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L122)):*
> ```Smalltalk
>                 bool[] completed = enumerators.Select(e => !e.MoveNext()).ToArray();
> 
>                 while (!completed.All(c => c))
> ```

Would it be possible to create/update the `completed` array and compute the completed count at the same time?


<!-- Sent from Reviewable.io -->

2024-11-13 23:15 UTC, Enkidu93 reviewed
Tracked https://github.com/sillsdev/machine/issues/272

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBbixOq8lLwZxlOpgs9:b7ltwiw)* status: 9 of 10 files reviewed, 20 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBbn2XJ6X8ZeMa4aG8k:bgve8u0) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should take a list of text corpora like `AlignMany`.
</blockquote></details>

So you want it to be used like `ChooseRandom([text1, text2])` not `AlignMany([text1, text2]).ChooseRandom()`? I'm sorry; I just hadn't a different idea of of the expectation.
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXS8hEAXBcbYIUFQo:-OBbjLuI0PhGgUgNAgvE:b-boqhc8) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The purpose of this interface is to use the decorator pattern to add support for corpus operations. This restricts what properties we can add to the interface. The `Corpora` property would be difficult to support in these operator decorators, so we should probably remove it.
</blockquote></details>

I see what you're saying. The issue is that `MergedCorpus` accesses `Corpora` and you asked me to use the interface not the `NParallelTextCorpus` class itself. Is the solution then to just have `INParallelTextCorpus` include `Versification` and `Texts` so that `MergedCorpus` doesn't need that visibility?
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 113 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXLiN8JEdQAWBHuMm:-OBbnqiz3c98jU-sNGJm:boyexb3) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L113)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like there is an extra brace here.
</blockquote></details>

Done. Thanks!
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 122 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbTysL0ByWMZXtAlpz:-OBbkXwEApBCOY-QKBvT:b-77gjyc) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L122)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Would it be possible to create/update the `completed` array and compute the completed count at the same time?
</blockquote></details>

I'm not sure what you mean. You mean `numberOfRemainingRows`?
___
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRjBRjEXGtv3c4h_Pa:-OBbkicu9p09A-WJ2TMm:b-xj4w9e) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L33)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should just be a readonly field.
</blockquote></details>

Is this what you mean?


<!-- Sent from Reviewable.io -->

2024-11-14 00:32 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: 6 of 10 files reviewed, 20 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 373 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBREHVm4XwhdI4bAQfy:-OBc4Y3u4MyuqKjxkHBj:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L373)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Alright, I'll try and move that. I don't think it should be too difficult, come to think of it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 14:26 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: 6 of 10 files reviewed, 20 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/ParallelTextCorpus.cs` line 33 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRjBRjEXGtv3c4h_Pa:-OBf3EMS89J0u_VvDngS:b-ekmlf2) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/ParallelTextCorpus.cs#L33)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Isn't it still public?
</blockquote></details>

No, you're right, John. I read property, not field - that's why I was confused. Thanks!


<!-- Sent from Reviewable.io -->

2024-11-14 15:32 UTC, ddaspit reviewed
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: 9 of 10 files reviewed, 19 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBfG4Bs0ECx4a6LTb1-:b-mr2zw0) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

So you want it to be used like `ChooseRandom([text1, text2])` not `AlignMany([text1, text2]).ChooseRandom()`? I'm sorry; I just hadn't a different idea of of the expectation.
</blockquote></details>

Yes, `NParallelTextCorpus` just feels like an implementation detail of `MergedCorpus`. The main purpose of `ChooseRandom` and `ChooseFirst` is to merge multiple text corpora into a single corpus. The API should reflect that. This also allows you to remove some requirements on `INParallelTextCorpus`, because you have direct access to the text corpora when creating `MergedCorpus`.
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXS8hEAXBcbYIUFQo:-OBfHMD70t3snzMFkP-9:b-apayz0) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L8)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see what you're saying. The issue is that `MergedCorpus` accesses `Corpora` and you asked me to use the interface not the `NParallelTextCorpus` class itself. Is the solution then to just have `INParallelTextCorpus` include `Versification` and `Texts` so that `MergedCorpus` doesn't need that visibility?
</blockquote></details>

See my comment above.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 122 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbTysL0ByWMZXtAlpz:-OBfHZTP-eUfVf3QDmIA:b-jn0f8h) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L122)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure what you mean. You mean `numberOfRemainingRows`?
</blockquote></details>

You can create `completed` in a loop instead of with `ToArray`. Inside of the loop, you can count the number of completed enumerators. The count is used in a couple of lines below. You can also use the count in the `while` check.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 557 at r6](https://reviewable.io/reviews/sillsdev/machine/270#-OBfH5cc-V9pSeyA3Py5:-OBfH5cc-V9pSeyA3Py6:b-5jqt0e) ([raw file](https://github.com/sillsdev/machine/blob/b3bd7b9cf60ed0f850ede7517c6ea59e917f145a/src/SIL.Machine/Corpora/CorporaExtensions.cs#L557)):*
> ```Smalltalk
>         }
> 
>         private class MergedCorpus : TextCorpusBase
> ```

Since this isn't just a decorator class, I would pull this out into a separate file and rename it `MergedTextCorpus`.


<!-- Sent from Reviewable.io -->

2024-11-14 15:50 UTC, Enkidu93 reviewed
Two general questions/comments:

- @johnml1135 , I don't think there's a reasonable, readable name for functions to extract some of the more complicated logic, so I just put comments and simplified where possible. If you can think of ones, I'm up for it, but 10-word function names seem even less clear than just the logic and a comment.
- @ddaspit @johnml1135 I don't think it makes sense of the range info to keep track of the same ref rows. They really aren't connected. John, you were the one who did a first pass at architecting a lot of this while I was away and you put the same ref rows in range info; what was the reason for that? I'm fine with it either way - just wondering what everyone else thinks/what the rationale was.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBfLdnTBPfk6qpwTLo-:b-nagbai)* status: 8 of 10 files reviewed, 19 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBfLKh6-t_WVJOjDiOA:b-7esgii) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, `NParallelTextCorpus` just feels like an implementation detail of `MergedCorpus`. The main purpose of `ChooseRandom` and `ChooseFirst` is to merge multiple text corpora into a single corpus. The API should reflect that. This also allows you to remove some requirements on `INParallelTextCorpus`, because you have direct access to the text corpora when creating `MergedCorpus`.
</blockquote></details>

OK, yep, then that'll make things easier.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 557 at r6](https://reviewable.io/reviews/sillsdev/machine/270#-OBfH5cc-V9pSeyA3Py5:-OBfLNB7AP7FBbOoyZIC:b-xxnm4i) ([raw file](https://github.com/sillsdev/machine/blob/b3bd7b9cf60ed0f850ede7517c6ea59e917f145a/src/SIL.Machine/Corpora/CorporaExtensions.cs#L557)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Since this isn't just a decorator class, I would pull this out into a separate file and rename it `MergedTextCorpus`.
</blockquote></details>

Alright, on it. 
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 122 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbTysL0ByWMZXtAlpz:-OBfLQ1E98M-ZHBBTd_S:br4beg8) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L122)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can create `completed` in a loop instead of with `ToArray`. Inside of the loop, you can count the number of completed enumerators. The count is used in a couple of lines below. You can also use the count in the `while` check.
</blockquote></details>

Oh, I see what you're saying. Yep, that's a good idea. Thanks!


<!-- Sent from Reviewable.io -->

2024-11-14 16:35 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 282 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR8DdQ22fuhcNWzed8:-OBfWqAZ0WIed753YWio:b-ul6gca) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L282)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This is the "permute all" part. I'll try and refactor a bit for clar9ity & efficiency.
</blockquote></details>

Could the permutation be broken out into a function, or at least given a comment explaining what is happening?


<!-- Sent from Reviewable.io -->

2024-11-14 16:56 UTC, johnml1135 commented
@Enkidu93  - please review the code coverage.  There are a few things I am noting:
* A lot of the exception handling is not being tested (this is likely ok - as it is low risk of not working).
* NParallelTextCorpus has the following testing needs:
  * //At least one of the non-min rows is not completed, is in a range, and has content
  * Line 342 - continue;
  * if (Versifications.All(v => v != null) && row.Refs.Count() == 0)
* NParallelTextRow - Invert
* CorporaExtensions:
  * IsTokenized
  * 2 if statements in GetRows
* NParallelCorpusBase - Count
* TextCorpusEnumerator - Reset
* CorpusAlignmentException - at least one exception each should be tested.





<!-- Sent from Reviewable.io -->

2024-11-14 20:38 UTC, Enkidu93 reviewed
OK, John, I've taken a look at a few of them and more fixes/additions are on the way - thanks!

Any thoughts about sameRefRows like asked about above?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBgO1pN33vxAgFcxYVQ:b-z1m187)* status: 5 of 12 files reviewed, 19 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBgNtT-8f001uGr30_m:bwyichq) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, yep, then that'll make things easier.
</blockquote></details>

Is this the way you wanted it? One question I have is in regards to the AllRows parameter: Is this the cleanest way to pass it or the best point at which to inject it?
___
*[`src/SIL.Machine/Corpora/INParallelTextCorpus.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbXS8hEAXBcbYIUFQo:-OBgOGKX7AaXxm8FnkAu:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/INParallelTextCorpus.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my comment above.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 282 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBR8DdQ22fuhcNWzed8:-OBgGD5p5IiQ4uRcall-:b-qx25zd) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L282)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Could the permutation be broken out into a function, or at least given a comment explaining what is happening?
</blockquote></details>

Done. I can add a comment as well if like
___
*[`src/SIL.Machine/Corpora/NParallelTextCorpus.cs` line 122 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbTysL0ByWMZXtAlpz:-OBgOIPk2a74YGEdDF0B:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/NParallelTextCorpus.cs#L122)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Oh, I see what you're saying. Yep, that's a good idea. Thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 21:04 UTC, johnml1135 commented
If you think they should be removed, just do it.  It seemed logical to me, but I only went half way down the rabbit hole.





<!-- Sent from Reviewable.io -->

2024-11-14 21:04 UTC, johnml1135 commented
If you thing sameRefRows should be removed from RangeInfo...





<!-- Sent from Reviewable.io -->

2024-11-14 21:15 UTC, johnml1135 commented
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRbRCDAH66Q0A5UTD6:-OBgWdQF0lLjTp5xr1yA:b-kq47dy) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L86)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Well, it's certainly possible that I'm confused haha :). Given that the implementation is consistent with the original ParallelTextCorpus, I figured it was correct, but maybe, @ddaspit, you could clarify the intended behavior (particularly in the case of N corpora). As I understand it, if all of the values of AllRows are false, the the only rows that are yielded are rows that exist in all corpora. However, if AllRows is true for a particular corpus, then all the rows of that corpus will have a parallel row yielded with the ref and content of that row regardless of whether the row is not in the other corpora or if the row ref were just mid-range in the other corpora. In regard to empty segments, you're right: I hadn't done any testing to do with that I don't think. I was mainly following the existing testing for ParallelTextCorpus and I don't know that there's any such test there either. What's the intended behavior in that case, @ddaspit?
</blockquote></details>

@ddaspit - can you bring in clarity - this may be the last issue...


<!-- Sent from Reviewable.io -->

2024-11-14 21:15 UTC, johnml1135 reviewed
> Reviewed 4 of 9 files at r2, 1 of 3 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-11-14 22:54 UTC, ddaspit reviewed
> Reviewed 1 of 9 files at r2, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBgpqgoCrb8_ioi5uBs:b-gio6fd) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this the way you wanted it? One question I have is in regards to the AllRows parameter: Is this the cleanest way to pass it or the best point at which to inject it?
</blockquote></details>

I don't think that `AllRows` is useful in this context. Do we need it? If not, we could simply not pass `AllRows` at all.
___
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRbRCDAH66Q0A5UTD6:-OBgrpu81oVb3L4yY03T:b-zhkcmf) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L86)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - can you bring in clarity - this may be the last issue...
</blockquote></details>

@Enkidu93's description of the behavior sounds correct. This assert is correct. There should be only one row that is returned.
___
*[`src/SIL.Machine/Corpora/MergedTextCorpus.cs` line 16 at r8](https://reviewable.io/reviews/sillsdev/machine/270#-OBgqg_788mNl2TIgXyj:-OBgqg_788mNl2TIgXyk:bx2aem6) ([raw file](https://github.com/sillsdev/machine/blob/14697e44ecbae90351cda05ab094ff13aef52d89/src/SIL.Machine/Corpora/MergedTextCorpus.cs#L16)):*
> ```Smalltalk
>         private readonly Random _random;
> 
>         public MergedTextCorpus(NParallelTextCorpus nParallelTextCorpus, MergeRule mergeRule, int seed)
> ```

I would have this accept an enumerable of text corpora instead of an `NParallelTextCorpus`. 


<!-- Sent from Reviewable.io -->

2024-11-14 23:42 UTC, johnml1135 commented
Once Damien's concerns are resolved, I'm fine with the changes.





<!-- Sent from Reviewable.io -->

2024-11-15 12:45 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBjouJ0-UhlkxHNC1F5:blvq4hd) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think that `AllRows` is useful in this context. Do we need it? If not, we could simply not pass `AllRows` at all.
</blockquote></details>

Let me see - "AllRows" is valuable when wanting to align to VRef.txt - so you get one line per vref entry (needed for AQUA as it relies on that specific format).  Beyond that, I can't think of any need for "AllRows".  And that should likely be it's own function, taking a single TextCorpus and then calling "AlignToVref" which would return a single TextCorpus with 1 entry per VRef.  Therefore, it would not be needed when "merging" or "choosing random" but merely in adding another extension to format a single existing corpus.  @ddaspit, does this sound right to you?


<!-- Sent from Reviewable.io -->

2024-11-15 12:51 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBjrW374b37G2iY00w5:b-xrn852) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Let me see - "AllRows" is valuable when wanting to align to VRef.txt - so you get one line per vref entry (needed for AQUA as it relies on that specific format).  Beyond that, I can't think of any need for "AllRows".  And that should likely be it's own function, taking a single TextCorpus and then calling "AlignToVref" which would return a single TextCorpus with 1 entry per VRef.  Therefore, it would not be needed when "merging" or "choosing random" but merely in adding another extension to format a single existing corpus.  @ddaspit, does this sound right to you?
</blockquote></details>

Actually, should we remove "AllRows" entirely from NParallelCorpus and rather just have a separate function that takes a single ITextCorpus to "AlignToVref"?


<!-- Sent from Reviewable.io -->

2024-11-15 13:12 UTC, johnml1135 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBjwwD052cf5qG6ciSn:b4l0sjn) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Actually, should we remove "AllRows" entirely from NParallelCorpus and rather just have a separate function that takes a single ITextCorpus to "AlignToVref"?
</blockquote></details>

We could also just rip out "AllRows" right now and then add the new function later, as it is not needed now.


<!-- Sent from Reviewable.io -->

2024-11-15 13:13 UTC, johnml1135 commented
Actually, should there be an ability to filter out non-scripture?  What is the best way to do that?





<!-- Sent from Reviewable.io -->

2024-11-15 14:35 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBkEQ9x3R8mQpqJ3x3S:b-pbej83) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

We could also just rip out "AllRows" right now and then add the new function later, as it is not needed now.
</blockquote></details>

We shouldn't remove `AllRows` altogether. We just don't need to pass it in this function. Also, there is already an "AlignToVref" function, it is called `ExtractScriptureCorpus`.


<!-- Sent from Reviewable.io -->

2024-11-15 14:36 UTC, Enkidu93 commented
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBkEdbkCTDwZTSYAaTH:b-qeqodq) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We shouldn't remove `AllRows` altogether. We just don't need to pass it in this function. Also, there is already an "AlignToVref" function, it is called `ExtractScriptureCorpus`.
</blockquote></details>

I think that `AllRows` is generally useful not just for us but perhaps even for others using the Machine library. One place we need it on the Serval side is when we align the pretranslate source and the train target: Since many rows will not have a target, this is necessary. Also, we use it currently (see the other PR) when doing the `AlignMany`s since each corpus has already been filtered by textId/scriptureRange, meaning that in many cases, they won't overlap. 


<!-- Sent from Reviewable.io -->

2024-11-15 14:41 UTC, Enkidu93 reviewed
If you look at the Serval PR, you can see an example (although it might be a bit outdated) of the intended use. At the moment, I'm filtering out non-Scripture where necessary on that side.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBkEUFY3rcZ8HFuE-Za:b-ixw5e5)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBkFOH2EM6x8zdHJKCL:b-54vp4k) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I think that `AllRows` is generally useful not just for us but perhaps even for others using the Machine library. One place we need it on the Serval side is when we align the pretranslate source and the train target: Since many rows will not have a target, this is necessary. Also, we use it currently (see the other PR) when doing the `AlignMany`s since each corpus has already been filtered by textId/scriptureRange, meaning that in many cases, they won't overlap.
</blockquote></details>

(Sorry, just seeing your new message, Damien!) To respond to your earlier message more directly, at the moment where we're using it in Serval (see the other PR), we're passing in `AllRows=[true,...,true]`, so maybe that ought to be the default? I'm not sure. It's less awkward to pass `AllRows` in with the API I was originally imagining; I'm only thinking of this now because it seems odd to pass in `AllRows` (which has to do with alignment) to a function that has to do with selection. 


<!-- Sent from Reviewable.io -->

2024-11-15 15:27 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/MergedTextCorpus.cs` line 16 at r8](https://reviewable.io/reviews/sillsdev/machine/270#-OBgqg_788mNl2TIgXyj:-OBkQols4frbIU6lGi02:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/14697e44ecbae90351cda05ab094ff13aef52d89/src/SIL.Machine/Corpora/MergedTextCorpus.cs#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would have this accept an enumerable of text corpora instead of an `NParallelTextCorpus`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 16:27 UTC, ddaspit reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBkcMjb3VZiT61BM3dd:bbao4qj) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

(Sorry, just seeing your new message, Damien!) To respond to your earlier message more directly, at the moment where we're using it in Serval (see the other PR), we're passing in `AllRows=[true,...,true]`, so maybe that ought to be the default? I'm not sure. It's less awkward to pass `AllRows` in with the API I was originally imagining; I'm only thinking of this now because it seems odd to pass in `AllRows` (which has to do with alignment) to a function that has to do with selection.
</blockquote></details>

Yes, I think we only need `AllRows=[true,...,true]` for the `MergedTextCorpus` to work properly.  We shouldn't need to pass in the `allRows` parameter.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 544 at r9](https://reviewable.io/reviews/sillsdev/machine/270#-OBkdVgs-krRQ6zDenXR:-OBkdVgs-krRQ6zDenXS:b-6y489b) ([raw file](https://github.com/sillsdev/machine/blob/2058d4d0a78c9132e08f1e3a3d840f20f8a1b8e1/src/SIL.Machine/Corpora/CorporaExtensions.cs#L544)):*
> ```Smalltalk
>             this IEnumerable<ITextCorpus> corpora,
>             IEnumerable<bool> allRows,
>             int seed
> ```

We should make `seed` an optional parameter.


<!-- Sent from Reviewable.io -->

2024-11-15 17:51 UTC, Enkidu93 reviewed
I think I've addressed everybody's comments. I'll wait for any more feedback you all have; let me know then I'll re-review and merge. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBkwbn04cEk8mPcbbrx:b-z7kdia)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 541 at r2](https://reviewable.io/reviews/sillsdev/machine/270#-OBbdimV5IkmqFIu0pn2:-OBkwXlm8cznSn2GfICb:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/e07cf64af0d429ad2c9d582f6efc7e48e8cce0b9/src/SIL.Machine/Corpora/CorporaExtensions.cs#L541)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, I think we only need `AllRows=[true,...,true]` for the `MergedTextCorpus` to work properly.  We shouldn't need to pass in the `allRows` parameter.
</blockquote></details>

Done.
___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 544 at r9](https://reviewable.io/reviews/sillsdev/machine/270#-OBkdVgs-krRQ6zDenXR:-OBkwUxi-NGqoftk3nvl:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/2058d4d0a78c9132e08f1e3a3d840f20f8a1b8e1/src/SIL.Machine/Corpora/CorporaExtensions.cs#L544)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should make `seed` an optional parameter.
</blockquote></details>

Done.
___
*[`tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/machine/270#-OBRbRCDAH66Q0A5UTD6:-OBkwVvy3IR5NIwIpVRR:b-896fix) ([raw file](https://github.com/sillsdev/machine/blob/7d47b9e131de248c08e5cc56d1688d5620aacf39/tests/SIL.Machine.Tests/Corpora/NParallelTextCorpusTests.cs#L86)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

@Enkidu93's description of the behavior sounds correct. This assert is correct. There should be only one row that is returned.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 17:52 UTC, Enkidu93 reviewed
(Actually, I think I'll add at least one test to cover a case John uncovered).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OBkwxlA08_sjkK-0A1w:b-xpr34m)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-11-15 21:56 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/SIL.Machine/Corpora/CorporaExtensions.cs` line 544 at r9](https://reviewable.io/reviews/sillsdev/machine/270#-OBkdVgs-krRQ6zDenXR:-OBloh-L4Qe2MQjg1IVp:b-j8e1op) ([raw file](https://github.com/sillsdev/machine/blob/2058d4d0a78c9132e08f1e3a3d840f20f8a1b8e1/src/SIL.Machine/Corpora/CorporaExtensions.cs#L544)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You forgot to make it optional in the `ChooseRandom` function.


<!-- Sent from Reviewable.io -->

2024-11-25 14:35 UTC, ddaspit reviewed
No, I don't remember what that check was for. I'm okay with the change, since the new test is testing for the correct behavior and all other tests pass.

> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OCYjd65CoEunKw5Afhz:b-q5zlkg)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-11-25 14:36 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Excellent work.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270#-:-OCYk1aH2gpsoaofOLyI:bvpj3vo)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-11-25 19:02 UTC, Enkidu93 reviewed
> Dismissed @johnml1135 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/machine/270)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-11-25 19:04 UTC, Enkidu93 commented
@johnml1135, it's saying I can't merge without your approval. I tried to dismiss you from the discussion because I think your question was answered, but it's still not letting me. If you could take a look when you have time, I'd appreciate it :)

2024-11-25 20:48 UTC, merged